#!/usr/bin/env python3
"""知识数据表：合成配方 / 工具进度链 / 材料类别（全技能共享，`_` 前缀不注册）。

设计原则（对齐 Issue #1）：
- 配方表按「物品 id」索引（minecraft:xxx），材料用「类别」→ 背包后缀匹配 + craft 展开
- LLM 只给目标物品 id（如 minecraft:oak_planks / minecraft:chest），kc 查配方
- 不可获取物品（命令方块/基岩等）明确列入 UNOBTAINABLE，报错时告知 LLM
- 新增配方/矿物只加一行，不改逻辑
"""

# ── 材料类别 → 背包匹配规则 ──────────────────────────────────────
# suffix 用于 count/find（endswith 匹配）；expand 是 craft 时的具体 id 展开策略
# expand: None = 按背包找到的具体 id（如 oak_log → oak_planks）；固定值 = 直接用该 id
MATERIAL_CATEGORIES = {
    # 木材链
    "log":          {"suffix": "_log",          "expand": None, "desc": "任意原木"},
    "planks":       {"suffix": "_planks",       "expand": None, "desc": "任意木板"},
    "stick":        {"suffix": "stick",         "expand": "minecraft:stick", "desc": "木棍"},
    "crafting_table": {"suffix": "crafting_table", "expand": "minecraft:crafting_table", "desc": "工作台"},
    "furnace":      {"suffix": "furnace",        "expand": "minecraft:furnace", "desc": "熔炉"},
    "chest":        {"suffix": "chest",          "expand": "minecraft:chest", "desc": "箱子"},
    "book":         {"suffix": "book",           "expand": "minecraft:book", "desc": "书"},
    "oak_slab":     {"suffix": "oak_slab",       "expand": "minecraft:oak_slab", "desc": "橡木台阶"},
    # 石材
    "cobblestone":  {"suffix": "cobblestone",   "expand": "minecraft:cobblestone", "desc": "圆石"},
    "stone":        {"suffix": "stone",          "expand": "minecraft:stone", "desc": "石头"},
    "stone_bricks": {"suffix": "stone_bricks",   "expand": "minecraft:stone_bricks", "desc": "石砖"},
    # 矿物/锭/宝石
    "coal":         {"suffix": "coal",           "expand": "minecraft:coal", "desc": "煤炭"},
    "iron_ingot":   {"suffix": "iron_ingot",     "expand": "minecraft:iron_ingot", "desc": "铁锭"},
    "gold_ingot":   {"suffix": "gold_ingot",     "expand": "minecraft:gold_ingot", "desc": "金锭"},
    "diamond":      {"suffix": "diamond",        "expand": "minecraft:diamond", "desc": "钻石"},
    "redstone":     {"suffix": "redstone",       "expand": "minecraft:redstone", "desc": "红石粉"},
    "lapis":        {"suffix": "lapis_lazuli",   "expand": "minecraft:lapis_lazuli", "desc": "青金石"},
    "emerald":      {"suffix": "emerald",        "expand": "minecraft:emerald", "desc": "绿宝石"},
    "gold_nugget":  {"suffix": "gold_nugget",    "expand": "minecraft:gold_nugget", "desc": "金粒"},
    "iron_nugget":  {"suffix": "iron_nugget",    "expand": "minecraft:iron_nugget", "desc": "铁粒"},
    "iron_block":   {"suffix": "iron_block",     "expand": "minecraft:iron_block", "desc": "铁块"},
    # 杂项材料
    "glass":        {"suffix": "glass",          "expand": "minecraft:glass", "desc": "玻璃"},
    "wool":         {"suffix": "_wool",          "expand": None, "desc": "任意羊毛"},
    "string":       {"suffix": "string",         "expand": "minecraft:string", "desc": "线"},
    "leather":      {"suffix": "leather",        "expand": "minecraft:leather", "desc": "皮革"},
    "feather":      {"suffix": "feather",        "expand": "minecraft:feather", "desc": "羽毛"},
    "bone":         {"suffix": "bone",           "expand": "minecraft:bone", "desc": "骨头"},
    "sugar_cane":   {"suffix": "sugar_cane",     "expand": "minecraft:sugar_cane", "desc": "甘蔗"},
    "paper":        {"suffix": "paper",          "expand": "minecraft:paper", "desc": "纸"},
    "flint":        {"suffix": "flint",          "expand": "minecraft:flint", "desc": "燧石"},
    "sand":         {"suffix": "sand",           "expand": "minecraft:sand", "desc": "沙子"},
    "clay_ball":    {"suffix": "clay_ball",      "expand": "minecraft:clay_ball", "desc": "黏土球"},
    "brick":        {"suffix": "brick",          "expand": "minecraft:brick", "desc": "红砖"},
    "bricks":       {"suffix": "bricks",         "expand": "minecraft:bricks", "desc": "砖块"},
    "netherrack":   {"suffix": "netherrack",     "expand": "minecraft:netherrack", "desc": "下界岩"},
    "blaze_powder": {"suffix": "blaze_powder",   "expand": "minecraft:blaze_powder", "desc": "烈焰粉"},
    "ender_pearl":  {"suffix": "ender_pearl",    "expand": "minecraft:ender_pearl", "desc": "末影珍珠"},
    "obsidian":     {"suffix": "obsidian",       "expand": "minecraft:obsidian", "desc": "黑曜石"},
    "glowstone_dust": {"suffix": "glowstone_dust", "expand": "minecraft:glowstone_dust", "desc": "萤石粉"},
    "torch":        {"suffix": "torch",          "expand": "minecraft:torch", "desc": "火把"},
    "pumpkin":      {"suffix": "pumpkin",        "expand": "minecraft:pumpkin", "desc": "南瓜"},
    "wheat":        {"suffix": "wheat",          "expand": "minecraft:wheat", "desc": "小麦"},
    "egg":          {"suffix": "egg",            "expand": "minecraft:egg", "desc": "鸡蛋"},
    "milk":         {"suffix": "milk_bucket",    "expand": "minecraft:milk_bucket", "desc": "牛奶桶"},
    "sugar":        {"suffix": "sugar",          "expand": "minecraft:sugar", "desc": "糖"},
    "cocoa_beans":  {"suffix": "cocoa_beans",    "expand": "minecraft:cocoa_beans", "desc": "可可豆"},
    "mushroom":     {"suffix": "_mushroom",      "expand": None, "desc": "蘑菇"},
    "nether_star":  {"suffix": "nether_star",    "expand": "minecraft:nether_star", "desc": "下界之星"},
    "ender_eye":    {"suffix": "ender_eye",      "expand": "minecraft:ender_eye", "desc": "末影之眼"},
    "bowl":         {"suffix": "bowl",           "expand": "minecraft:bowl", "desc": "碗"},
}

# ── 合成配方表（物品 id → 配方）──────────────────────────────────
# materials: {材料类别: 数量}；grid: "2x2"=背包个人格 / "3x3"=工作台
# yield: 一次合成产出数量；desc: 说明（注入 LLM）
RECIPES = {
    "minecraft:bed":          {"materials": {"wool": 3, "planks": 3}, "grid": "3x3", "yield": 1, "desc": "羊毛+木板→床"},
    "minecraft:acacia_boat": {"materials": {"minecraft:acacia_planks": 5}, "grid": "3x3", "yield": 1},
    "minecraft:acacia_button": {"materials": {"minecraft:acacia_planks": 1}, "grid": "2x2", "yield": 1},
    "minecraft:acacia_chest_boat": {"materials": {"minecraft:chest": 1, "minecraft:acacia_boat": 1}, "grid": "2x2", "yield": 1},
    "minecraft:acacia_door": {"materials": {"minecraft:acacia_planks": 6}, "grid": "3x3", "yield": 3},
    "minecraft:acacia_fence": {"materials": {"minecraft:acacia_planks": 4, "minecraft:stick": 2}, "grid": "3x3", "yield": 3},
    "minecraft:acacia_fence_gate": {"materials": {"minecraft:stick": 4, "minecraft:acacia_planks": 2}, "grid": "3x3", "yield": 1},
    "minecraft:acacia_hanging_sign": {"materials": {"minecraft:chain": 2, "minecraft:stripped_acacia_log": 6}, "grid": "3x3", "yield": 6},
    "minecraft:acacia_planks": {"materials": {"minecraft:acacia_log": 1}, "grid": "2x2", "yield": 4},
    "minecraft:acacia_pressure_plate": {"materials": {"minecraft:acacia_planks": 2}, "grid": "2x2", "yield": 1},
    "minecraft:acacia_sign": {"materials": {"minecraft:acacia_planks": 6, "minecraft:stick": 1}, "grid": "3x3", "yield": 3},
    "minecraft:acacia_slab": {"materials": {"minecraft:acacia_planks": 3}, "grid": "3x3", "yield": 6},
    "minecraft:acacia_stairs": {"materials": {"minecraft:acacia_planks": 6}, "grid": "3x3", "yield": 4},
    "minecraft:acacia_trapdoor": {"materials": {"minecraft:acacia_planks": 6}, "grid": "3x3", "yield": 2},
    "minecraft:acacia_wood": {"materials": {"minecraft:acacia_log": 4}, "grid": "2x2", "yield": 3},
    "minecraft:activator_rail": {"materials": {"minecraft:iron_ingot": 6, "minecraft:stick": 2, "minecraft:redstone_torch": 1}, "grid": "3x3", "yield": 6},
    "minecraft:amethyst_block": {"materials": {"minecraft:amethyst_shard": 4}, "grid": "2x2", "yield": 1},
    "minecraft:andesite": {"materials": {"minecraft:diorite": 1, "minecraft:cobblestone": 1}, "grid": "2x2", "yield": 2},
    "minecraft:andesite_slab": {"materials": {"minecraft:andesite": 3}, "grid": "3x3", "yield": 6},
    "minecraft:andesite_stairs": {"materials": {"minecraft:andesite": 6}, "grid": "3x3", "yield": 4},
    "minecraft:andesite_wall": {"materials": {"minecraft:andesite": 6}, "grid": "3x3", "yield": 6},
    "minecraft:anvil": {"materials": {"minecraft:iron_block": 3, "minecraft:iron_ingot": 4}, "grid": "3x3", "yield": 1},
    "minecraft:armor_stand": {"materials": {"minecraft:stick": 6, "minecraft:smooth_stone_slab": 1}, "grid": "3x3", "yield": 1},
    "minecraft:arrow": {"materials": {"minecraft:flint": 1, "minecraft:stick": 1, "minecraft:feather": 1}, "grid": "3x3", "yield": 4},
    "minecraft:bamboo_block": {"materials": {"minecraft:bamboo": 9}, "grid": "2x2", "yield": 1},
    "minecraft:bamboo_button": {"materials": {"minecraft:bamboo_planks": 1}, "grid": "2x2", "yield": 1},
    "minecraft:bamboo_chest_raft": {"materials": {"minecraft:chest": 1, "minecraft:bamboo_raft": 1}, "grid": "2x2", "yield": 1},
    "minecraft:bamboo_door": {"materials": {"minecraft:bamboo_planks": 6}, "grid": "3x3", "yield": 3},
    "minecraft:bamboo_fence": {"materials": {"minecraft:bamboo_planks": 4, "minecraft:stick": 2}, "grid": "3x3", "yield": 3},
    "minecraft:bamboo_fence_gate": {"materials": {"minecraft:stick": 4, "minecraft:bamboo_planks": 2}, "grid": "3x3", "yield": 1},
    "minecraft:bamboo_hanging_sign": {"materials": {"minecraft:chain": 2, "minecraft:stripped_bamboo_block": 6}, "grid": "3x3", "yield": 6},
    "minecraft:bamboo_mosaic": {"materials": {"minecraft:bamboo_slab": 2}, "grid": "2x2", "yield": 1},
    "minecraft:bamboo_mosaic_slab": {"materials": {"minecraft:bamboo_mosaic": 3}, "grid": "3x3", "yield": 6},
    "minecraft:bamboo_mosaic_stairs": {"materials": {"minecraft:bamboo_mosaic": 6}, "grid": "3x3", "yield": 4},
    "minecraft:bamboo_planks": {"materials": {"minecraft:bamboo_block": 1}, "grid": "2x2", "yield": 2},
    "minecraft:bamboo_pressure_plate": {"materials": {"minecraft:bamboo_planks": 2}, "grid": "2x2", "yield": 1},
    "minecraft:bamboo_raft": {"materials": {"minecraft:bamboo_planks": 5}, "grid": "3x3", "yield": 1},
    "minecraft:bamboo_sign": {"materials": {"minecraft:bamboo_planks": 6, "minecraft:stick": 1}, "grid": "3x3", "yield": 3},
    "minecraft:bamboo_slab": {"materials": {"minecraft:bamboo_planks": 3}, "grid": "3x3", "yield": 6},
    "minecraft:bamboo_stairs": {"materials": {"minecraft:bamboo_planks": 6}, "grid": "3x3", "yield": 4},
    "minecraft:bamboo_trapdoor": {"materials": {"minecraft:bamboo_planks": 6}, "grid": "3x3", "yield": 2},
    "minecraft:barrel": {"materials": {"minecraft:oak_planks": 6, "minecraft:oak_slab": 2}, "grid": "3x3", "yield": 1},
    "minecraft:beacon": {"materials": {"minecraft:glass": 5, "minecraft:nether_star": 1, "minecraft:obsidian": 3}, "grid": "3x3", "yield": 1},
    "minecraft:beehive": {"materials": {"minecraft:oak_planks": 6, "minecraft:honeycomb": 3}, "grid": "3x3", "yield": 1},
    "minecraft:beetroot_soup": {"materials": {"minecraft:bowl": 1, "minecraft:beetroot": 6}, "grid": "2x2", "yield": 1},
    "minecraft:birch_boat": {"materials": {"minecraft:birch_planks": 5}, "grid": "3x3", "yield": 1},
    "minecraft:birch_button": {"materials": {"minecraft:birch_planks": 1}, "grid": "2x2", "yield": 1},
    "minecraft:birch_chest_boat": {"materials": {"minecraft:chest": 1, "minecraft:birch_boat": 1}, "grid": "2x2", "yield": 1},
    "minecraft:birch_door": {"materials": {"minecraft:birch_planks": 6}, "grid": "3x3", "yield": 3},
    "minecraft:birch_fence": {"materials": {"minecraft:birch_planks": 4, "minecraft:stick": 2}, "grid": "3x3", "yield": 3},
    "minecraft:birch_fence_gate": {"materials": {"minecraft:stick": 4, "minecraft:birch_planks": 2}, "grid": "3x3", "yield": 1},
    "minecraft:birch_hanging_sign": {"materials": {"minecraft:chain": 2, "minecraft:stripped_birch_log": 6}, "grid": "3x3", "yield": 6},
    "minecraft:birch_planks": {"materials": {"minecraft:birch_log": 1}, "grid": "2x2", "yield": 4},
    "minecraft:birch_pressure_plate": {"materials": {"minecraft:birch_planks": 2}, "grid": "2x2", "yield": 1},
    "minecraft:birch_sign": {"materials": {"minecraft:birch_planks": 6, "minecraft:stick": 1}, "grid": "3x3", "yield": 3},
    "minecraft:birch_slab": {"materials": {"minecraft:birch_planks": 3}, "grid": "3x3", "yield": 6},
    "minecraft:birch_stairs": {"materials": {"minecraft:birch_planks": 6}, "grid": "3x3", "yield": 4},
    "minecraft:birch_trapdoor": {"materials": {"minecraft:birch_planks": 6}, "grid": "3x3", "yield": 2},
    "minecraft:birch_wood": {"materials": {"minecraft:birch_log": 4}, "grid": "2x2", "yield": 3},
    "minecraft:black_banner": {"materials": {"minecraft:black_wool": 6, "minecraft:stick": 1}, "grid": "3x3", "yield": 1},
    "minecraft:black_bed": {"materials": {"minecraft:black_wool": 3, "minecraft:oak_planks": 3}, "grid": "3x3", "yield": 1},
    "minecraft:black_candle": {"materials": {"minecraft:candle": 1, "minecraft:black_dye": 1}, "grid": "2x2", "yield": 1},
    "minecraft:black_carpet": {"materials": {"minecraft:black_wool": 2}, "grid": "2x2", "yield": 3},
    "minecraft:black_concrete_powder": {"materials": {"minecraft:black_dye": 1, "minecraft:sand": 4, "minecraft:gravel": 4}, "grid": "2x2", "yield": 8},
    "minecraft:black_dye": {"materials": {"minecraft:ink_sac": 1}, "grid": "2x2", "yield": 1},
    "minecraft:black_stained_glass": {"materials": {"minecraft:glass": 8, "minecraft:black_dye": 1}, "grid": "3x3", "yield": 8},
    "minecraft:black_stained_glass_pane": {"materials": {"minecraft:black_stained_glass": 6}, "grid": "3x3", "yield": 16},
    "minecraft:black_terracotta": {"materials": {"minecraft:terracotta": 8, "minecraft:black_dye": 1}, "grid": "3x3", "yield": 8},
    "minecraft:black_wool": {"materials": {"minecraft:black_dye": 1, "minecraft:blue_wool": 1}, "grid": "2x2", "yield": 1},
    "minecraft:blackstone_slab": {"materials": {"minecraft:blackstone": 3}, "grid": "3x3", "yield": 6},
    "minecraft:blackstone_stairs": {"materials": {"minecraft:blackstone": 6}, "grid": "3x3", "yield": 4},
    "minecraft:blackstone_wall": {"materials": {"minecraft:blackstone": 6}, "grid": "3x3", "yield": 6},
    "minecraft:blast_furnace": {"materials": {"minecraft:iron_ingot": 5, "minecraft:furnace": 1, "minecraft:smooth_stone": 3}, "grid": "3x3", "yield": 1},
    "minecraft:blaze_powder": {"materials": {"minecraft:blaze_rod": 1}, "grid": "2x2", "yield": 2},
    "minecraft:blue_banner": {"materials": {"minecraft:blue_wool": 6, "minecraft:stick": 1}, "grid": "3x3", "yield": 1},
    "minecraft:blue_bed": {"materials": {"minecraft:blue_wool": 3, "minecraft:oak_planks": 3}, "grid": "3x3", "yield": 1},
    "minecraft:blue_candle": {"materials": {"minecraft:candle": 1, "minecraft:blue_dye": 1}, "grid": "2x2", "yield": 1},
    "minecraft:blue_carpet": {"materials": {"minecraft:blue_wool": 2}, "grid": "2x2", "yield": 3},
    "minecraft:blue_concrete_powder": {"materials": {"minecraft:blue_dye": 1, "minecraft:sand": 4, "minecraft:gravel": 4}, "grid": "2x2", "yield": 8},
    "minecraft:blue_dye": {"materials": {"minecraft:lapis_lazuli": 1}, "grid": "2x2", "yield": 1},
    "minecraft:blue_ice": {"materials": {"minecraft:packed_ice": 9}, "grid": "2x2", "yield": 1},
    "minecraft:blue_stained_glass": {"materials": {"minecraft:glass": 8, "minecraft:blue_dye": 1}, "grid": "3x3", "yield": 8},
    "minecraft:blue_stained_glass_pane": {"materials": {"minecraft:blue_stained_glass": 6}, "grid": "3x3", "yield": 16},
    "minecraft:blue_terracotta": {"materials": {"minecraft:terracotta": 8, "minecraft:blue_dye": 1}, "grid": "3x3", "yield": 8},
    "minecraft:blue_wool": {"materials": {"minecraft:blue_dye": 1, "minecraft:black_wool": 1}, "grid": "2x2", "yield": 1},
    "minecraft:bone_block": {"materials": {"minecraft:bone_meal": 9}, "grid": "3x3", "yield": 1},
    "minecraft:bone_meal": {"materials": {"minecraft:bone": 1}, "grid": "2x2", "yield": 3},
    "minecraft:book": {"materials": {"minecraft:paper": 3, "minecraft:leather": 1}, "grid": "2x2", "yield": 1},
    "minecraft:bookshelf": {"materials": {"minecraft:oak_planks": 6, "minecraft:book": 3}, "grid": "3x3", "yield": 1},
    "minecraft:bow": {"materials": {"minecraft:stick": 3, "minecraft:string": 3}, "grid": "3x3", "yield": 1},
    "minecraft:bowl": {"materials": {"minecraft:oak_planks": 3}, "grid": "3x3", "yield": 4},
    "minecraft:bread": {"materials": {"minecraft:wheat": 3}, "grid": "3x3", "yield": 1},
    "minecraft:brewing_stand": {"materials": {"minecraft:blaze_rod": 1, "minecraft:cobblestone": 3}, "grid": "3x3", "yield": 1},
    "minecraft:brick_slab": {"materials": {"minecraft:bricks": 3}, "grid": "3x3", "yield": 6},
    "minecraft:brick_stairs": {"materials": {"minecraft:bricks": 6}, "grid": "3x3", "yield": 4},
    "minecraft:brick_wall": {"materials": {"minecraft:bricks": 6}, "grid": "3x3", "yield": 6},
    "minecraft:bricks": {"materials": {"minecraft:brick": 4}, "grid": "2x2", "yield": 1},
    "minecraft:brown_banner": {"materials": {"minecraft:brown_wool": 6, "minecraft:stick": 1}, "grid": "3x3", "yield": 1},
    "minecraft:brown_bed": {"materials": {"minecraft:brown_wool": 3, "minecraft:oak_planks": 3}, "grid": "3x3", "yield": 1},
    "minecraft:brown_candle": {"materials": {"minecraft:candle": 1, "minecraft:brown_dye": 1}, "grid": "2x2", "yield": 1},
    "minecraft:brown_carpet": {"materials": {"minecraft:brown_wool": 2}, "grid": "2x2", "yield": 3},
    "minecraft:brown_concrete_powder": {"materials": {"minecraft:brown_dye": 1, "minecraft:sand": 4, "minecraft:gravel": 4}, "grid": "2x2", "yield": 8},
    "minecraft:brown_dye": {"materials": {"minecraft:cocoa_beans": 1}, "grid": "2x2", "yield": 1},
    "minecraft:brown_stained_glass": {"materials": {"minecraft:glass": 8, "minecraft:brown_dye": 1}, "grid": "3x3", "yield": 8},
    "minecraft:brown_stained_glass_pane": {"materials": {"minecraft:brown_stained_glass": 6}, "grid": "3x3", "yield": 16},
    "minecraft:brown_terracotta": {"materials": {"minecraft:terracotta": 8, "minecraft:brown_dye": 1}, "grid": "3x3", "yield": 8},
    "minecraft:brown_wool": {"materials": {"minecraft:brown_dye": 1, "minecraft:black_wool": 1}, "grid": "2x2", "yield": 1},
    "minecraft:brush": {"materials": {"minecraft:feather": 1, "minecraft:copper_ingot": 1, "minecraft:stick": 1}, "grid": "3x3", "yield": 1},
    "minecraft:bucket": {"materials": {"minecraft:iron_ingot": 3}, "grid": "3x3", "yield": 1},
    "minecraft:cake": {"materials": {"minecraft:milk_bucket": 3, "minecraft:sugar": 2, "minecraft:egg": 1, "minecraft:wheat": 3}, "grid": "3x3", "yield": 1},
    "minecraft:calibrated_sculk_sensor": {"materials": {"minecraft:amethyst_shard": 3, "minecraft:sculk_sensor": 1}, "grid": "3x3", "yield": 1},
    "minecraft:campfire": {"materials": {"minecraft:stick": 3, "minecraft:coal": 1, "minecraft:dark_oak_log": 3}, "grid": "3x3", "yield": 1},
    "minecraft:candle": {"materials": {"minecraft:string": 1, "minecraft:honeycomb": 1}, "grid": "2x2", "yield": 1},
    "minecraft:carrot_on_a_stick": {"materials": {"minecraft:fishing_rod": 1, "minecraft:carrot": 1}, "grid": "2x2", "yield": 1},
    "minecraft:cartography_table": {"materials": {"minecraft:paper": 2, "minecraft:oak_planks": 4}, "grid": "3x3", "yield": 1},
    "minecraft:cauldron": {"materials": {"minecraft:iron_ingot": 7}, "grid": "3x3", "yield": 1},
    "minecraft:chain": {"materials": {"minecraft:iron_nugget": 2, "minecraft:iron_ingot": 1}, "grid": "3x3", "yield": 1},
    "minecraft:cherry_boat": {"materials": {"minecraft:cherry_planks": 5}, "grid": "3x3", "yield": 1},
    "minecraft:cherry_button": {"materials": {"minecraft:cherry_planks": 1}, "grid": "2x2", "yield": 1},
    "minecraft:cherry_chest_boat": {"materials": {"minecraft:chest": 1, "minecraft:cherry_boat": 1}, "grid": "2x2", "yield": 1},
    "minecraft:cherry_door": {"materials": {"minecraft:cherry_planks": 6}, "grid": "3x3", "yield": 3},
    "minecraft:cherry_fence": {"materials": {"minecraft:cherry_planks": 4, "minecraft:stick": 2}, "grid": "3x3", "yield": 3},
    "minecraft:cherry_fence_gate": {"materials": {"minecraft:stick": 4, "minecraft:cherry_planks": 2}, "grid": "3x3", "yield": 1},
    "minecraft:cherry_hanging_sign": {"materials": {"minecraft:chain": 2, "minecraft:stripped_cherry_log": 6}, "grid": "3x3", "yield": 6},
    "minecraft:cherry_planks": {"materials": {"minecraft:cherry_log": 1}, "grid": "2x2", "yield": 4},
    "minecraft:cherry_pressure_plate": {"materials": {"minecraft:cherry_planks": 2}, "grid": "2x2", "yield": 1},
    "minecraft:cherry_sign": {"materials": {"minecraft:cherry_planks": 6, "minecraft:stick": 1}, "grid": "3x3", "yield": 3},
    "minecraft:cherry_slab": {"materials": {"minecraft:cherry_planks": 3}, "grid": "3x3", "yield": 6},
    "minecraft:cherry_stairs": {"materials": {"minecraft:cherry_planks": 6}, "grid": "3x3", "yield": 4},
    "minecraft:cherry_trapdoor": {"materials": {"minecraft:cherry_planks": 6}, "grid": "3x3", "yield": 2},
    "minecraft:cherry_wood": {"materials": {"minecraft:cherry_log": 4}, "grid": "2x2", "yield": 3},
    "minecraft:chest": {"materials": {"minecraft:oak_planks": 8}, "grid": "3x3", "yield": 1},
    "minecraft:chest_minecart": {"materials": {"minecraft:chest": 1, "minecraft:minecart": 1}, "grid": "2x2", "yield": 1},
    "minecraft:chiseled_bookshelf": {"materials": {"minecraft:oak_planks": 6, "minecraft:oak_slab": 3}, "grid": "3x3", "yield": 1},
    "minecraft:chiseled_deepslate": {"materials": {"minecraft:cobbled_deepslate_slab": 2}, "grid": "2x2", "yield": 1},
    "minecraft:chiseled_nether_bricks": {"materials": {"minecraft:nether_brick_slab": 2}, "grid": "2x2", "yield": 1},
    "minecraft:chiseled_polished_blackstone": {"materials": {"minecraft:polished_blackstone_slab": 2}, "grid": "2x2", "yield": 1},
    "minecraft:chiseled_quartz_block": {"materials": {"minecraft:quartz_slab": 2}, "grid": "2x2", "yield": 1},
    "minecraft:chiseled_red_sandstone": {"materials": {"minecraft:red_sandstone_slab": 2}, "grid": "2x2", "yield": 1},
    "minecraft:chiseled_sandstone": {"materials": {"minecraft:sandstone_slab": 2}, "grid": "2x2", "yield": 1},
    "minecraft:chiseled_stone_bricks": {"materials": {"minecraft:stone_brick_slab": 2}, "grid": "2x2", "yield": 1},
    "minecraft:clay": {"materials": {"minecraft:clay_ball": 4}, "grid": "2x2", "yield": 1},
    "minecraft:clock": {"materials": {"minecraft:gold_ingot": 4, "minecraft:redstone": 1}, "grid": "3x3", "yield": 1},
    "minecraft:coal_block": {"materials": {"minecraft:coal": 9}, "grid": "3x3", "yield": 1},
    "minecraft:coarse_dirt": {"materials": {"minecraft:dirt": 2, "minecraft:gravel": 2}, "grid": "2x2", "yield": 4},
    "minecraft:cobbled_deepslate_slab": {"materials": {"minecraft:cobbled_deepslate": 3}, "grid": "3x3", "yield": 6},
    "minecraft:cobbled_deepslate_stairs": {"materials": {"minecraft:cobbled_deepslate": 6}, "grid": "3x3", "yield": 4},
    "minecraft:cobbled_deepslate_wall": {"materials": {"minecraft:cobbled_deepslate": 6}, "grid": "3x3", "yield": 6},
    "minecraft:cobblestone_slab": {"materials": {"minecraft:cobblestone": 3}, "grid": "3x3", "yield": 6},
    "minecraft:cobblestone_stairs": {"materials": {"minecraft:cobblestone": 6}, "grid": "3x3", "yield": 4},
    "minecraft:cobblestone_wall": {"materials": {"minecraft:cobblestone": 6}, "grid": "3x3", "yield": 6},
    "minecraft:comparator": {"materials": {"minecraft:redstone_torch": 3, "minecraft:quartz": 1, "minecraft:stone": 3}, "grid": "3x3", "yield": 1},
    "minecraft:compass": {"materials": {"minecraft:iron_ingot": 4, "minecraft:redstone": 1}, "grid": "3x3", "yield": 1},
    "minecraft:composter": {"materials": {"minecraft:oak_slab": 7}, "grid": "3x3", "yield": 1},
    "minecraft:conduit": {"materials": {"minecraft:nautilus_shell": 8, "minecraft:heart_of_the_sea": 1}, "grid": "3x3", "yield": 1},
    "minecraft:cookie": {"materials": {"minecraft:wheat": 2, "minecraft:cocoa_beans": 1}, "grid": "3x3", "yield": 8},
    "minecraft:copper_block": {"materials": {"minecraft:copper_ingot": 9}, "grid": "3x3", "yield": 1},
    "minecraft:crafting_table": {"materials": {"minecraft:oak_planks": 4}, "grid": "2x2", "yield": 1},
    "minecraft:creeper_banner_pattern": {"materials": {"minecraft:paper": 1, "minecraft:creeper_head": 1}, "grid": "2x2", "yield": 1},
    "minecraft:crimson_button": {"materials": {"minecraft:crimson_planks": 1}, "grid": "2x2", "yield": 1},
    "minecraft:crimson_door": {"materials": {"minecraft:crimson_planks": 6}, "grid": "3x3", "yield": 3},
    "minecraft:crimson_fence": {"materials": {"minecraft:crimson_planks": 4, "minecraft:stick": 2}, "grid": "3x3", "yield": 3},
    "minecraft:crimson_fence_gate": {"materials": {"minecraft:stick": 4, "minecraft:crimson_planks": 2}, "grid": "3x3", "yield": 1},
    "minecraft:crimson_hanging_sign": {"materials": {"minecraft:chain": 2, "minecraft:stripped_crimson_stem": 6}, "grid": "3x3", "yield": 6},
    "minecraft:crimson_hyphae": {"materials": {"minecraft:crimson_stem": 4}, "grid": "2x2", "yield": 3},
    "minecraft:crimson_planks": {"materials": {"minecraft:crimson_stem": 1}, "grid": "2x2", "yield": 4},
    "minecraft:crimson_pressure_plate": {"materials": {"minecraft:crimson_planks": 2}, "grid": "2x2", "yield": 1},
    "minecraft:crimson_sign": {"materials": {"minecraft:crimson_planks": 6, "minecraft:stick": 1}, "grid": "3x3", "yield": 3},
    "minecraft:crimson_slab": {"materials": {"minecraft:crimson_planks": 3}, "grid": "3x3", "yield": 6},
    "minecraft:crimson_stairs": {"materials": {"minecraft:crimson_planks": 6}, "grid": "3x3", "yield": 4},
    "minecraft:crimson_trapdoor": {"materials": {"minecraft:crimson_planks": 6}, "grid": "3x3", "yield": 2},
    "minecraft:crossbow": {"materials": {"minecraft:stick": 3, "minecraft:iron_ingot": 1, "minecraft:string": 2, "minecraft:tripwire_hook": 1}, "grid": "3x3", "yield": 1},
    "minecraft:cut_copper": {"materials": {"minecraft:copper_block": 4}, "grid": "2x2", "yield": 4},
    "minecraft:cut_copper_slab": {"materials": {"minecraft:cut_copper": 3}, "grid": "3x3", "yield": 6},
    "minecraft:cut_copper_stairs": {"materials": {"minecraft:cut_copper": 6}, "grid": "3x3", "yield": 4},
    "minecraft:cut_red_sandstone": {"materials": {"minecraft:red_sandstone": 4}, "grid": "2x2", "yield": 4},
    "minecraft:cut_red_sandstone_slab": {"materials": {"minecraft:cut_red_sandstone": 3}, "grid": "3x3", "yield": 6},
    "minecraft:cut_sandstone": {"materials": {"minecraft:sandstone": 4}, "grid": "2x2", "yield": 4},
    "minecraft:cut_sandstone_slab": {"materials": {"minecraft:cut_sandstone": 3}, "grid": "3x3", "yield": 6},
    "minecraft:cyan_banner": {"materials": {"minecraft:cyan_wool": 6, "minecraft:stick": 1}, "grid": "3x3", "yield": 1},
    "minecraft:cyan_bed": {"materials": {"minecraft:cyan_wool": 3, "minecraft:oak_planks": 3}, "grid": "3x3", "yield": 1},
    "minecraft:cyan_candle": {"materials": {"minecraft:candle": 1, "minecraft:cyan_dye": 1}, "grid": "2x2", "yield": 1},
    "minecraft:cyan_carpet": {"materials": {"minecraft:cyan_wool": 2}, "grid": "2x2", "yield": 3},
    "minecraft:cyan_concrete_powder": {"materials": {"minecraft:cyan_dye": 1, "minecraft:sand": 4, "minecraft:gravel": 4}, "grid": "2x2", "yield": 8},
    "minecraft:cyan_dye": {"materials": {"minecraft:pitcher_plant": 1}, "grid": "2x2", "yield": 2},
    "minecraft:cyan_stained_glass": {"materials": {"minecraft:glass": 8, "minecraft:cyan_dye": 1}, "grid": "3x3", "yield": 8},
    "minecraft:cyan_stained_glass_pane": {"materials": {"minecraft:cyan_stained_glass": 6}, "grid": "3x3", "yield": 16},
    "minecraft:cyan_terracotta": {"materials": {"minecraft:terracotta": 8, "minecraft:cyan_dye": 1}, "grid": "3x3", "yield": 8},
    "minecraft:cyan_wool": {"materials": {"minecraft:cyan_dye": 1, "minecraft:black_wool": 1}, "grid": "2x2", "yield": 1},
    "minecraft:dark_oak_boat": {"materials": {"minecraft:dark_oak_planks": 5}, "grid": "3x3", "yield": 1},
    "minecraft:dark_oak_button": {"materials": {"minecraft:dark_oak_planks": 1}, "grid": "2x2", "yield": 1},
    "minecraft:dark_oak_chest_boat": {"materials": {"minecraft:chest": 1, "minecraft:dark_oak_boat": 1}, "grid": "2x2", "yield": 1},
    "minecraft:dark_oak_door": {"materials": {"minecraft:dark_oak_planks": 6}, "grid": "3x3", "yield": 3},
    "minecraft:dark_oak_fence": {"materials": {"minecraft:dark_oak_planks": 4, "minecraft:stick": 2}, "grid": "3x3", "yield": 3},
    "minecraft:dark_oak_fence_gate": {"materials": {"minecraft:stick": 4, "minecraft:dark_oak_planks": 2}, "grid": "3x3", "yield": 1},
    "minecraft:dark_oak_hanging_sign": {"materials": {"minecraft:chain": 2, "minecraft:stripped_dark_oak_log": 6}, "grid": "3x3", "yield": 6},
    "minecraft:dark_oak_planks": {"materials": {"minecraft:dark_oak_log": 1}, "grid": "2x2", "yield": 4},
    "minecraft:dark_oak_pressure_plate": {"materials": {"minecraft:dark_oak_planks": 2}, "grid": "2x2", "yield": 1},
    "minecraft:dark_oak_sign": {"materials": {"minecraft:dark_oak_planks": 6, "minecraft:stick": 1}, "grid": "3x3", "yield": 3},
    "minecraft:dark_oak_slab": {"materials": {"minecraft:dark_oak_planks": 3}, "grid": "3x3", "yield": 6},
    "minecraft:dark_oak_stairs": {"materials": {"minecraft:dark_oak_planks": 6}, "grid": "3x3", "yield": 4},
    "minecraft:dark_oak_trapdoor": {"materials": {"minecraft:dark_oak_planks": 6}, "grid": "3x3", "yield": 2},
    "minecraft:dark_oak_wood": {"materials": {"minecraft:dark_oak_log": 4}, "grid": "2x2", "yield": 3},
    "minecraft:dark_prismarine": {"materials": {"minecraft:prismarine_shard": 8, "minecraft:black_dye": 1}, "grid": "3x3", "yield": 1},
    "minecraft:dark_prismarine_slab": {"materials": {"minecraft:dark_prismarine": 3}, "grid": "3x3", "yield": 6},
    "minecraft:dark_prismarine_stairs": {"materials": {"minecraft:dark_prismarine": 6}, "grid": "3x3", "yield": 4},
    "minecraft:daylight_detector": {"materials": {"minecraft:glass": 3, "minecraft:quartz": 3, "minecraft:oak_slab": 3}, "grid": "3x3", "yield": 1},
    "minecraft:decorated_pot": {"materials": {"minecraft:brick": 4}, "grid": "3x3", "yield": 1},
    "minecraft:deepslate_brick_slab": {"materials": {"minecraft:deepslate_bricks": 3}, "grid": "3x3", "yield": 6},
    "minecraft:deepslate_brick_stairs": {"materials": {"minecraft:deepslate_bricks": 6}, "grid": "3x3", "yield": 4},
    "minecraft:deepslate_brick_wall": {"materials": {"minecraft:deepslate_bricks": 6}, "grid": "3x3", "yield": 6},
    "minecraft:deepslate_bricks": {"materials": {"minecraft:polished_deepslate": 4}, "grid": "2x2", "yield": 4},
    "minecraft:deepslate_tile_slab": {"materials": {"minecraft:deepslate_tiles": 3}, "grid": "3x3", "yield": 6},
    "minecraft:deepslate_tile_stairs": {"materials": {"minecraft:deepslate_tiles": 6}, "grid": "3x3", "yield": 4},
    "minecraft:deepslate_tile_wall": {"materials": {"minecraft:deepslate_tiles": 6}, "grid": "3x3", "yield": 6},
    "minecraft:deepslate_tiles": {"materials": {"minecraft:deepslate_bricks": 4}, "grid": "2x2", "yield": 4},
    "minecraft:detector_rail": {"materials": {"minecraft:iron_ingot": 6, "minecraft:stone_pressure_plate": 1, "minecraft:redstone": 1}, "grid": "3x3", "yield": 6},
    "minecraft:diamond_axe": {"materials": {"minecraft:diamond": 3, "minecraft:stick": 2}, "grid": "3x3", "yield": 1},
    "minecraft:diamond_block": {"materials": {"minecraft:diamond": 9}, "grid": "3x3", "yield": 1},
    "minecraft:diamond_boots": {"materials": {"minecraft:diamond": 4}, "grid": "3x3", "yield": 1},
    "minecraft:diamond_chestplate": {"materials": {"minecraft:diamond": 8}, "grid": "3x3", "yield": 1},
    "minecraft:diamond_helmet": {"materials": {"minecraft:diamond": 5}, "grid": "3x3", "yield": 1},
    "minecraft:diamond_hoe": {"materials": {"minecraft:diamond": 2, "minecraft:stick": 2}, "grid": "3x3", "yield": 1},
    "minecraft:diamond_leggings": {"materials": {"minecraft:diamond": 7}, "grid": "3x3", "yield": 1},
    "minecraft:diamond_pickaxe": {"materials": {"minecraft:diamond": 3, "minecraft:stick": 2}, "grid": "3x3", "yield": 1},
    "minecraft:diamond_shovel": {"materials": {"minecraft:diamond": 1, "minecraft:stick": 2}, "grid": "3x3", "yield": 1},
    "minecraft:diamond_sword": {"materials": {"minecraft:diamond": 2, "minecraft:stick": 1}, "grid": "3x3", "yield": 1},
    "minecraft:diorite": {"materials": {"minecraft:cobblestone": 2, "minecraft:quartz": 2}, "grid": "2x2", "yield": 2},
    "minecraft:diorite_slab": {"materials": {"minecraft:diorite": 3}, "grid": "3x3", "yield": 6},
    "minecraft:diorite_stairs": {"materials": {"minecraft:diorite": 6}, "grid": "3x3", "yield": 4},
    "minecraft:diorite_wall": {"materials": {"minecraft:diorite": 6}, "grid": "3x3", "yield": 6},
    "minecraft:dispenser": {"materials": {"minecraft:cobblestone": 7, "minecraft:bow": 1, "minecraft:redstone": 1}, "grid": "3x3", "yield": 1},
    "minecraft:dried_kelp": {"materials": {"minecraft:dried_kelp_block": 1}, "grid": "2x2", "yield": 9},
    "minecraft:dried_kelp_block": {"materials": {"minecraft:dried_kelp": 9}, "grid": "3x3", "yield": 1},
    "minecraft:dripstone_block": {"materials": {"minecraft:pointed_dripstone": 4}, "grid": "2x2", "yield": 1},
    "minecraft:dropper": {"materials": {"minecraft:cobblestone": 7, "minecraft:redstone": 1}, "grid": "3x3", "yield": 1},
    "minecraft:emerald_block": {"materials": {"minecraft:emerald": 9}, "grid": "3x3", "yield": 1},
    "minecraft:enchanting_table": {"materials": {"minecraft:book": 1, "minecraft:diamond": 2, "minecraft:obsidian": 4}, "grid": "3x3", "yield": 1},
    "minecraft:end_crystal": {"materials": {"minecraft:glass": 7, "minecraft:ender_eye": 1, "minecraft:ghast_tear": 1}, "grid": "3x3", "yield": 1},
    "minecraft:end_rod": {"materials": {"minecraft:blaze_rod": 1, "minecraft:popped_chorus_fruit": 1}, "grid": "2x2", "yield": 4},
    "minecraft:end_stone_brick_slab": {"materials": {"minecraft:end_stone_bricks": 3}, "grid": "3x3", "yield": 6},
    "minecraft:end_stone_brick_stairs": {"materials": {"minecraft:end_stone_bricks": 6}, "grid": "3x3", "yield": 4},
    "minecraft:end_stone_brick_wall": {"materials": {"minecraft:end_stone_bricks": 6}, "grid": "3x3", "yield": 6},
    "minecraft:end_stone_bricks": {"materials": {"minecraft:end_stone": 4}, "grid": "2x2", "yield": 4},
    "minecraft:ender_chest": {"materials": {"minecraft:obsidian": 8, "minecraft:ender_eye": 1}, "grid": "3x3", "yield": 1},
    "minecraft:ender_eye": {"materials": {"minecraft:ender_pearl": 1, "minecraft:blaze_powder": 1}, "grid": "2x2", "yield": 1},
    "minecraft:exposed_cut_copper": {"materials": {"minecraft:exposed_copper": 4}, "grid": "2x2", "yield": 4},
    "minecraft:exposed_cut_copper_slab": {"materials": {"minecraft:exposed_cut_copper": 3}, "grid": "3x3", "yield": 6},
    "minecraft:exposed_cut_copper_stairs": {"materials": {"minecraft:exposed_cut_copper": 6}, "grid": "3x3", "yield": 4},
    "minecraft:fermented_spider_eye": {"materials": {"minecraft:spider_eye": 1, "minecraft:brown_mushroom": 1, "minecraft:sugar": 1}, "grid": "2x2", "yield": 1},
    "minecraft:fire_charge": {"materials": {"minecraft:gunpowder": 1, "minecraft:blaze_powder": 1, "minecraft:coal": 1}, "grid": "2x2", "yield": 3},
    "minecraft:firework_rocket": {"materials": {"minecraft:gunpowder": 1, "minecraft:paper": 1}, "grid": "2x2", "yield": 3},
    "minecraft:fishing_rod": {"materials": {"minecraft:stick": 3, "minecraft:string": 2}, "grid": "3x3", "yield": 1},
    "minecraft:fletching_table": {"materials": {"minecraft:flint": 2, "minecraft:oak_planks": 4}, "grid": "3x3", "yield": 1},
    "minecraft:flint_and_steel": {"materials": {"minecraft:iron_ingot": 1, "minecraft:flint": 1}, "grid": "2x2", "yield": 1},
    "minecraft:flower_banner_pattern": {"materials": {"minecraft:paper": 1, "minecraft:oxeye_daisy": 1}, "grid": "2x2", "yield": 1},
    "minecraft:flower_pot": {"materials": {"minecraft:brick": 3}, "grid": "3x3", "yield": 1},
    "minecraft:furnace": {"materials": {"minecraft:cobblestone": 8}, "grid": "3x3", "yield": 1},
    "minecraft:furnace_minecart": {"materials": {"minecraft:furnace": 1, "minecraft:minecart": 1}, "grid": "2x2", "yield": 1},
    "minecraft:glass_bottle": {"materials": {"minecraft:glass": 3}, "grid": "3x3", "yield": 3},
    "minecraft:glass_pane": {"materials": {"minecraft:glass": 6}, "grid": "3x3", "yield": 16},
    "minecraft:glistering_melon_slice": {"materials": {"minecraft:gold_nugget": 8, "minecraft:melon_slice": 1}, "grid": "3x3", "yield": 1},
    "minecraft:glow_item_frame": {"materials": {"minecraft:item_frame": 1, "minecraft:glow_ink_sac": 1}, "grid": "2x2", "yield": 1},
    "minecraft:glowstone": {"materials": {"minecraft:glowstone_dust": 4}, "grid": "2x2", "yield": 1},
    "minecraft:gold_block": {"materials": {"minecraft:gold_ingot": 9}, "grid": "3x3", "yield": 1},
    "minecraft:gold_nugget": {"materials": {"minecraft:gold_ingot": 1}, "grid": "2x2", "yield": 9},
    "minecraft:golden_apple": {"materials": {"minecraft:gold_ingot": 8, "minecraft:apple": 1}, "grid": "3x3", "yield": 1},
    "minecraft:golden_axe": {"materials": {"minecraft:gold_ingot": 3, "minecraft:stick": 2}, "grid": "3x3", "yield": 1},
    "minecraft:golden_boots": {"materials": {"minecraft:gold_ingot": 4}, "grid": "3x3", "yield": 1},
    "minecraft:golden_carrot": {"materials": {"minecraft:gold_nugget": 8, "minecraft:carrot": 1}, "grid": "3x3", "yield": 1},
    "minecraft:golden_chestplate": {"materials": {"minecraft:gold_ingot": 8}, "grid": "3x3", "yield": 1},
    "minecraft:golden_helmet": {"materials": {"minecraft:gold_ingot": 5}, "grid": "3x3", "yield": 1},
    "minecraft:golden_hoe": {"materials": {"minecraft:gold_ingot": 2, "minecraft:stick": 2}, "grid": "3x3", "yield": 1},
    "minecraft:golden_leggings": {"materials": {"minecraft:gold_ingot": 7}, "grid": "3x3", "yield": 1},
    "minecraft:golden_pickaxe": {"materials": {"minecraft:gold_ingot": 3, "minecraft:stick": 2}, "grid": "3x3", "yield": 1},
    "minecraft:golden_shovel": {"materials": {"minecraft:gold_ingot": 1, "minecraft:stick": 2}, "grid": "3x3", "yield": 1},
    "minecraft:golden_sword": {"materials": {"minecraft:gold_ingot": 2, "minecraft:stick": 1}, "grid": "3x3", "yield": 1},
    "minecraft:granite": {"materials": {"minecraft:diorite": 1, "minecraft:quartz": 1}, "grid": "2x2", "yield": 1},
    "minecraft:granite_slab": {"materials": {"minecraft:granite": 3}, "grid": "3x3", "yield": 6},
    "minecraft:granite_stairs": {"materials": {"minecraft:granite": 6}, "grid": "3x3", "yield": 4},
    "minecraft:granite_wall": {"materials": {"minecraft:granite": 6}, "grid": "3x3", "yield": 6},
    "minecraft:gray_banner": {"materials": {"minecraft:gray_wool": 6, "minecraft:stick": 1}, "grid": "3x3", "yield": 1},
    "minecraft:gray_bed": {"materials": {"minecraft:gray_dye": 1, "minecraft:black_bed": 1}, "grid": "2x2", "yield": 1},
    "minecraft:gray_candle": {"materials": {"minecraft:candle": 1, "minecraft:gray_dye": 1}, "grid": "2x2", "yield": 1},
    "minecraft:gray_carpet": {"materials": {"minecraft:gray_wool": 2}, "grid": "2x2", "yield": 3},
    "minecraft:gray_concrete_powder": {"materials": {"minecraft:gray_dye": 1, "minecraft:sand": 4, "minecraft:gravel": 4}, "grid": "2x2", "yield": 8},
    "minecraft:gray_dye": {"materials": {"minecraft:black_dye": 1, "minecraft:white_dye": 1}, "grid": "2x2", "yield": 2},
    "minecraft:gray_stained_glass": {"materials": {"minecraft:glass": 8, "minecraft:gray_dye": 1}, "grid": "3x3", "yield": 8},
    "minecraft:gray_stained_glass_pane": {"materials": {"minecraft:gray_stained_glass": 6}, "grid": "3x3", "yield": 16},
    "minecraft:gray_terracotta": {"materials": {"minecraft:terracotta": 8, "minecraft:gray_dye": 1}, "grid": "3x3", "yield": 8},
    "minecraft:gray_wool": {"materials": {"minecraft:gray_dye": 1, "minecraft:black_wool": 1}, "grid": "2x2", "yield": 1},
    "minecraft:green_banner": {"materials": {"minecraft:green_wool": 6, "minecraft:stick": 1}, "grid": "3x3", "yield": 1},
    "minecraft:green_bed": {"materials": {"minecraft:green_dye": 1, "minecraft:black_bed": 1}, "grid": "2x2", "yield": 1},
    "minecraft:green_candle": {"materials": {"minecraft:candle": 1, "minecraft:green_dye": 1}, "grid": "2x2", "yield": 1},
    "minecraft:green_carpet": {"materials": {"minecraft:green_wool": 2}, "grid": "2x2", "yield": 3},
    "minecraft:green_concrete_powder": {"materials": {"minecraft:green_dye": 1, "minecraft:sand": 4, "minecraft:gravel": 4}, "grid": "2x2", "yield": 8},
    "minecraft:green_stained_glass": {"materials": {"minecraft:glass": 8, "minecraft:green_dye": 1}, "grid": "3x3", "yield": 8},
    "minecraft:green_stained_glass_pane": {"materials": {"minecraft:green_stained_glass": 6}, "grid": "3x3", "yield": 16},
    "minecraft:green_terracotta": {"materials": {"minecraft:terracotta": 8, "minecraft:green_dye": 1}, "grid": "3x3", "yield": 8},
    "minecraft:green_wool": {"materials": {"minecraft:green_dye": 1, "minecraft:black_wool": 1}, "grid": "2x2", "yield": 1},
    "minecraft:grindstone": {"materials": {"minecraft:stick": 2, "minecraft:stone_slab": 1, "minecraft:oak_planks": 2}, "grid": "3x3", "yield": 1},
    "minecraft:hay_block": {"materials": {"minecraft:wheat": 9}, "grid": "2x2", "yield": 1},
    "minecraft:heavy_weighted_pressure_plate": {"materials": {"minecraft:iron_ingot": 2}, "grid": "2x2", "yield": 1},
    "minecraft:honey_block": {"materials": {"minecraft:honey_bottle": 4}, "grid": "2x2", "yield": 1},
    "minecraft:honey_bottle": {"materials": {"minecraft:honey_block": 1, "minecraft:glass_bottle": 4}, "grid": "2x2", "yield": 4},
    "minecraft:honeycomb_block": {"materials": {"minecraft:honeycomb": 4}, "grid": "2x2", "yield": 1},
    "minecraft:hopper": {"materials": {"minecraft:iron_ingot": 5, "minecraft:chest": 1}, "grid": "3x3", "yield": 1},
    "minecraft:hopper_minecart": {"materials": {"minecraft:hopper": 1, "minecraft:minecart": 1}, "grid": "2x2", "yield": 1},
    "minecraft:iron_axe": {"materials": {"minecraft:iron_ingot": 3, "minecraft:stick": 2}, "grid": "3x3", "yield": 1},
    "minecraft:iron_bars": {"materials": {"minecraft:iron_ingot": 6}, "grid": "3x3", "yield": 16},
    "minecraft:iron_block": {"materials": {"minecraft:iron_ingot": 9}, "grid": "3x3", "yield": 1},
    "minecraft:iron_boots": {"materials": {"minecraft:iron_ingot": 4}, "grid": "3x3", "yield": 1},
    "minecraft:iron_chestplate": {"materials": {"minecraft:iron_ingot": 8}, "grid": "3x3", "yield": 1},
    "minecraft:iron_door": {"materials": {"minecraft:iron_ingot": 6}, "grid": "3x3", "yield": 3},
    "minecraft:iron_helmet": {"materials": {"minecraft:iron_ingot": 5}, "grid": "3x3", "yield": 1},
    "minecraft:iron_hoe": {"materials": {"minecraft:iron_ingot": 2, "minecraft:stick": 2}, "grid": "3x3", "yield": 1},
    "minecraft:iron_leggings": {"materials": {"minecraft:iron_ingot": 7}, "grid": "3x3", "yield": 1},
    "minecraft:iron_nugget": {"materials": {"minecraft:iron_ingot": 1}, "grid": "2x2", "yield": 9},
    "minecraft:iron_pickaxe": {"materials": {"minecraft:iron_ingot": 3, "minecraft:stick": 2}, "grid": "3x3", "yield": 1},
    "minecraft:iron_shovel": {"materials": {"minecraft:iron_ingot": 1, "minecraft:stick": 2}, "grid": "3x3", "yield": 1},
    "minecraft:iron_sword": {"materials": {"minecraft:iron_ingot": 2, "minecraft:stick": 1}, "grid": "3x3", "yield": 1},
    "minecraft:iron_trapdoor": {"materials": {"minecraft:iron_ingot": 4}, "grid": "2x2", "yield": 1},
    "minecraft:item_frame": {"materials": {"minecraft:stick": 8, "minecraft:leather": 1}, "grid": "3x3", "yield": 1},
    "minecraft:jack_o_lantern": {"materials": {"minecraft:carved_pumpkin": 1, "minecraft:torch": 1}, "grid": "2x2", "yield": 1},
    "minecraft:jukebox": {"materials": {"minecraft:oak_planks": 8, "minecraft:diamond": 1}, "grid": "3x3", "yield": 1},
    "minecraft:jungle_boat": {"materials": {"minecraft:jungle_planks": 5}, "grid": "3x3", "yield": 1},
    "minecraft:jungle_button": {"materials": {"minecraft:jungle_planks": 1}, "grid": "2x2", "yield": 1},
    "minecraft:jungle_chest_boat": {"materials": {"minecraft:chest": 1, "minecraft:jungle_boat": 1}, "grid": "2x2", "yield": 1},
    "minecraft:jungle_door": {"materials": {"minecraft:jungle_planks": 6}, "grid": "3x3", "yield": 3},
    "minecraft:jungle_fence": {"materials": {"minecraft:jungle_planks": 4, "minecraft:stick": 2}, "grid": "3x3", "yield": 3},
    "minecraft:jungle_fence_gate": {"materials": {"minecraft:stick": 4, "minecraft:jungle_planks": 2}, "grid": "3x3", "yield": 1},
    "minecraft:jungle_hanging_sign": {"materials": {"minecraft:chain": 2, "minecraft:stripped_jungle_log": 6}, "grid": "3x3", "yield": 6},
    "minecraft:jungle_planks": {"materials": {"minecraft:jungle_log": 1}, "grid": "2x2", "yield": 4},
    "minecraft:jungle_pressure_plate": {"materials": {"minecraft:jungle_planks": 2}, "grid": "2x2", "yield": 1},
    "minecraft:jungle_sign": {"materials": {"minecraft:jungle_planks": 6, "minecraft:stick": 1}, "grid": "3x3", "yield": 3},
    "minecraft:jungle_slab": {"materials": {"minecraft:jungle_planks": 3}, "grid": "3x3", "yield": 6},
    "minecraft:jungle_stairs": {"materials": {"minecraft:jungle_planks": 6}, "grid": "3x3", "yield": 4},
    "minecraft:jungle_trapdoor": {"materials": {"minecraft:jungle_planks": 6}, "grid": "3x3", "yield": 2},
    "minecraft:jungle_wood": {"materials": {"minecraft:jungle_log": 4}, "grid": "2x2", "yield": 3},
    "minecraft:ladder": {"materials": {"minecraft:stick": 7}, "grid": "3x3", "yield": 3},
    "minecraft:lantern": {"materials": {"minecraft:iron_nugget": 8, "minecraft:torch": 1}, "grid": "3x3", "yield": 1},
    "minecraft:lapis_block": {"materials": {"minecraft:lapis_lazuli": 9}, "grid": "3x3", "yield": 1},
    "minecraft:lead": {"materials": {"minecraft:string": 4, "minecraft:slime_ball": 1}, "grid": "3x3", "yield": 2},
    "minecraft:leather": {"materials": {"minecraft:rabbit_hide": 4}, "grid": "2x2", "yield": 1},
    "minecraft:leather_boots": {"materials": {"minecraft:leather": 4}, "grid": "3x3", "yield": 1},
    "minecraft:leather_chestplate": {"materials": {"minecraft:leather": 8}, "grid": "3x3", "yield": 1},
    "minecraft:leather_helmet": {"materials": {"minecraft:leather": 5}, "grid": "3x3", "yield": 1},
    "minecraft:leather_horse_armor": {"materials": {"minecraft:leather": 7}, "grid": "3x3", "yield": 1},
    "minecraft:leather_leggings": {"materials": {"minecraft:leather": 7}, "grid": "3x3", "yield": 1},
    "minecraft:lectern": {"materials": {"minecraft:oak_slab": 4, "minecraft:bookshelf": 1}, "grid": "3x3", "yield": 1},
    "minecraft:lever": {"materials": {"minecraft:stick": 1, "minecraft:cobblestone": 1}, "grid": "2x2", "yield": 1},
    "minecraft:light_blue_banner": {"materials": {"minecraft:light_blue_wool": 6, "minecraft:stick": 1}, "grid": "3x3", "yield": 1},
    "minecraft:light_blue_bed": {"materials": {"minecraft:light_blue_dye": 1, "minecraft:black_bed": 1}, "grid": "2x2", "yield": 1},
    "minecraft:light_blue_candle": {"materials": {"minecraft:candle": 1, "minecraft:light_blue_dye": 1}, "grid": "2x2", "yield": 1},
    "minecraft:light_blue_carpet": {"materials": {"minecraft:light_blue_wool": 2}, "grid": "2x2", "yield": 3},
    "minecraft:light_blue_concrete_powder": {"materials": {"minecraft:light_blue_dye": 1, "minecraft:sand": 4, "minecraft:gravel": 4}, "grid": "2x2", "yield": 8},
    "minecraft:light_blue_dye": {"materials": {"minecraft:blue_orchid": 1}, "grid": "2x2", "yield": 1},
    "minecraft:light_blue_stained_glass": {"materials": {"minecraft:glass": 8, "minecraft:light_blue_dye": 1}, "grid": "3x3", "yield": 8},
    "minecraft:light_blue_stained_glass_pane": {"materials": {"minecraft:light_blue_stained_glass": 6}, "grid": "3x3", "yield": 16},
    "minecraft:light_blue_terracotta": {"materials": {"minecraft:terracotta": 8, "minecraft:light_blue_dye": 1}, "grid": "3x3", "yield": 8},
    "minecraft:light_blue_wool": {"materials": {"minecraft:light_blue_dye": 1, "minecraft:black_wool": 1}, "grid": "2x2", "yield": 1},
    "minecraft:light_gray_banner": {"materials": {"minecraft:light_gray_wool": 6, "minecraft:stick": 1}, "grid": "3x3", "yield": 1},
    "minecraft:light_gray_bed": {"materials": {"minecraft:light_gray_dye": 1, "minecraft:black_bed": 1}, "grid": "2x2", "yield": 1},
    "minecraft:light_gray_candle": {"materials": {"minecraft:candle": 1, "minecraft:light_gray_dye": 1}, "grid": "2x2", "yield": 1},
    "minecraft:light_gray_carpet": {"materials": {"minecraft:light_gray_wool": 2}, "grid": "2x2", "yield": 3},
    "minecraft:light_gray_concrete_powder": {"materials": {"minecraft:light_gray_dye": 1, "minecraft:sand": 4, "minecraft:gravel": 4}, "grid": "2x2", "yield": 8},
    "minecraft:light_gray_dye": {"materials": {"minecraft:azure_bluet": 1}, "grid": "2x2", "yield": 1},
    "minecraft:light_gray_stained_glass": {"materials": {"minecraft:glass": 8, "minecraft:light_gray_dye": 1}, "grid": "3x3", "yield": 8},
    "minecraft:light_gray_stained_glass_pane": {"materials": {"minecraft:light_gray_stained_glass": 6}, "grid": "3x3", "yield": 16},
    "minecraft:light_gray_terracotta": {"materials": {"minecraft:terracotta": 8, "minecraft:light_gray_dye": 1}, "grid": "3x3", "yield": 8},
    "minecraft:light_gray_wool": {"materials": {"minecraft:light_gray_dye": 1, "minecraft:black_wool": 1}, "grid": "2x2", "yield": 1},
    "minecraft:light_weighted_pressure_plate": {"materials": {"minecraft:gold_ingot": 2}, "grid": "2x2", "yield": 1},
    "minecraft:lightning_rod": {"materials": {"minecraft:copper_ingot": 3}, "grid": "3x3", "yield": 1},
    "minecraft:lime_banner": {"materials": {"minecraft:lime_wool": 6, "minecraft:stick": 1}, "grid": "3x3", "yield": 1},
    "minecraft:lime_bed": {"materials": {"minecraft:lime_dye": 1, "minecraft:black_bed": 1}, "grid": "2x2", "yield": 1},
    "minecraft:lime_candle": {"materials": {"minecraft:candle": 1, "minecraft:lime_dye": 1}, "grid": "2x2", "yield": 1},
    "minecraft:lime_carpet": {"materials": {"minecraft:lime_wool": 2}, "grid": "2x2", "yield": 3},
    "minecraft:lime_concrete_powder": {"materials": {"minecraft:lime_dye": 1, "minecraft:sand": 4, "minecraft:gravel": 4}, "grid": "2x2", "yield": 8},
    "minecraft:lime_dye": {"materials": {"minecraft:green_dye": 1, "minecraft:white_dye": 1}, "grid": "2x2", "yield": 2},
    "minecraft:lime_stained_glass": {"materials": {"minecraft:glass": 8, "minecraft:lime_dye": 1}, "grid": "3x3", "yield": 8},
    "minecraft:lime_stained_glass_pane": {"materials": {"minecraft:lime_stained_glass": 6}, "grid": "3x3", "yield": 16},
    "minecraft:lime_terracotta": {"materials": {"minecraft:terracotta": 8, "minecraft:lime_dye": 1}, "grid": "3x3", "yield": 8},
    "minecraft:lime_wool": {"materials": {"minecraft:lime_dye": 1, "minecraft:black_wool": 1}, "grid": "2x2", "yield": 1},
    "minecraft:lodestone": {"materials": {"minecraft:chiseled_stone_bricks": 8, "minecraft:netherite_ingot": 1}, "grid": "3x3", "yield": 1},
    "minecraft:loom": {"materials": {"minecraft:string": 2, "minecraft:oak_planks": 2}, "grid": "2x2", "yield": 1},
    "minecraft:magenta_banner": {"materials": {"minecraft:magenta_wool": 6, "minecraft:stick": 1}, "grid": "3x3", "yield": 1},
    "minecraft:magenta_bed": {"materials": {"minecraft:magenta_dye": 1, "minecraft:black_bed": 1}, "grid": "2x2", "yield": 1},
    "minecraft:magenta_candle": {"materials": {"minecraft:candle": 1, "minecraft:magenta_dye": 1}, "grid": "2x2", "yield": 1},
    "minecraft:magenta_carpet": {"materials": {"minecraft:magenta_wool": 2}, "grid": "2x2", "yield": 3},
    "minecraft:magenta_concrete_powder": {"materials": {"minecraft:magenta_dye": 1, "minecraft:sand": 4, "minecraft:gravel": 4}, "grid": "2x2", "yield": 8},
    "minecraft:magenta_dye": {"materials": {"minecraft:allium": 1}, "grid": "2x2", "yield": 1},
    "minecraft:magenta_stained_glass": {"materials": {"minecraft:glass": 8, "minecraft:magenta_dye": 1}, "grid": "3x3", "yield": 8},
    "minecraft:magenta_stained_glass_pane": {"materials": {"minecraft:magenta_stained_glass": 6}, "grid": "3x3", "yield": 16},
    "minecraft:magenta_terracotta": {"materials": {"minecraft:terracotta": 8, "minecraft:magenta_dye": 1}, "grid": "3x3", "yield": 8},
    "minecraft:magenta_wool": {"materials": {"minecraft:magenta_dye": 1, "minecraft:black_wool": 1}, "grid": "2x2", "yield": 1},
    "minecraft:magma_block": {"materials": {"minecraft:magma_cream": 4}, "grid": "2x2", "yield": 1},
    "minecraft:magma_cream": {"materials": {"minecraft:blaze_powder": 1, "minecraft:slime_ball": 1}, "grid": "2x2", "yield": 1},
    "minecraft:mangrove_boat": {"materials": {"minecraft:mangrove_planks": 5}, "grid": "3x3", "yield": 1},
    "minecraft:mangrove_button": {"materials": {"minecraft:mangrove_planks": 1}, "grid": "2x2", "yield": 1},
    "minecraft:mangrove_chest_boat": {"materials": {"minecraft:chest": 1, "minecraft:mangrove_boat": 1}, "grid": "2x2", "yield": 1},
    "minecraft:mangrove_door": {"materials": {"minecraft:mangrove_planks": 6}, "grid": "3x3", "yield": 3},
    "minecraft:mangrove_fence": {"materials": {"minecraft:mangrove_planks": 4, "minecraft:stick": 2}, "grid": "3x3", "yield": 3},
    "minecraft:mangrove_fence_gate": {"materials": {"minecraft:stick": 4, "minecraft:mangrove_planks": 2}, "grid": "3x3", "yield": 1},
    "minecraft:mangrove_hanging_sign": {"materials": {"minecraft:chain": 2, "minecraft:stripped_mangrove_log": 6}, "grid": "3x3", "yield": 6},
    "minecraft:mangrove_planks": {"materials": {"minecraft:mangrove_log": 1}, "grid": "2x2", "yield": 4},
    "minecraft:mangrove_pressure_plate": {"materials": {"minecraft:mangrove_planks": 2}, "grid": "2x2", "yield": 1},
    "minecraft:mangrove_sign": {"materials": {"minecraft:mangrove_planks": 6, "minecraft:stick": 1}, "grid": "3x3", "yield": 3},
    "minecraft:mangrove_slab": {"materials": {"minecraft:mangrove_planks": 3}, "grid": "3x3", "yield": 6},
    "minecraft:mangrove_stairs": {"materials": {"minecraft:mangrove_planks": 6}, "grid": "3x3", "yield": 4},
    "minecraft:mangrove_trapdoor": {"materials": {"minecraft:mangrove_planks": 6}, "grid": "3x3", "yield": 2},
    "minecraft:mangrove_wood": {"materials": {"minecraft:mangrove_log": 4}, "grid": "2x2", "yield": 3},
    "minecraft:map": {"materials": {"minecraft:paper": 8, "minecraft:compass": 1}, "grid": "3x3", "yield": 1},
    "minecraft:melon": {"materials": {"minecraft:melon_slice": 9}, "grid": "2x2", "yield": 1},
    "minecraft:melon_seeds": {"materials": {"minecraft:melon_slice": 1}, "grid": "2x2", "yield": 1},
    "minecraft:minecart": {"materials": {"minecraft:iron_ingot": 5}, "grid": "3x3", "yield": 1},
    "minecraft:mojang_banner_pattern": {"materials": {"minecraft:paper": 1, "minecraft:enchanted_golden_apple": 1}, "grid": "2x2", "yield": 1},
    "minecraft:moss_carpet": {"materials": {"minecraft:moss_block": 2}, "grid": "2x2", "yield": 3},
    "minecraft:mossy_cobblestone": {"materials": {"minecraft:cobblestone": 1, "minecraft:moss_block": 1}, "grid": "2x2", "yield": 1},
    "minecraft:mossy_cobblestone_slab": {"materials": {"minecraft:mossy_cobblestone": 3}, "grid": "3x3", "yield": 6},
    "minecraft:mossy_cobblestone_stairs": {"materials": {"minecraft:mossy_cobblestone": 6}, "grid": "3x3", "yield": 4},
    "minecraft:mossy_cobblestone_wall": {"materials": {"minecraft:mossy_cobblestone": 6}, "grid": "3x3", "yield": 6},
    "minecraft:mossy_stone_brick_slab": {"materials": {"minecraft:mossy_stone_bricks": 3}, "grid": "3x3", "yield": 6},
    "minecraft:mossy_stone_brick_stairs": {"materials": {"minecraft:mossy_stone_bricks": 6}, "grid": "3x3", "yield": 4},
    "minecraft:mossy_stone_brick_wall": {"materials": {"minecraft:mossy_stone_bricks": 6}, "grid": "3x3", "yield": 6},
    "minecraft:mossy_stone_bricks": {"materials": {"minecraft:stone_bricks": 1, "minecraft:moss_block": 1}, "grid": "2x2", "yield": 1},
    "minecraft:mud_brick_slab": {"materials": {"minecraft:mud_bricks": 3}, "grid": "3x3", "yield": 6},
    "minecraft:mud_brick_stairs": {"materials": {"minecraft:mud_bricks": 6}, "grid": "3x3", "yield": 4},
    "minecraft:mud_brick_wall": {"materials": {"minecraft:mud_bricks": 6}, "grid": "3x3", "yield": 6},
    "minecraft:mud_bricks": {"materials": {"minecraft:packed_mud": 4}, "grid": "2x2", "yield": 4},
    "minecraft:muddy_mangrove_roots": {"materials": {"minecraft:mud": 1, "minecraft:mangrove_roots": 1}, "grid": "2x2", "yield": 1},
    "minecraft:mushroom_stew": {"materials": {"minecraft:brown_mushroom": 1, "minecraft:red_mushroom": 1, "minecraft:bowl": 1}, "grid": "2x2", "yield": 1},
    "minecraft:music_disc_5": {"materials": {"minecraft:disc_fragment_5": 9}, "grid": "2x2", "yield": 1},
    "minecraft:nether_brick_fence": {"materials": {"minecraft:nether_bricks": 4, "minecraft:nether_brick": 2}, "grid": "3x3", "yield": 6},
    "minecraft:nether_brick_slab": {"materials": {"minecraft:nether_bricks": 3}, "grid": "3x3", "yield": 6},
    "minecraft:nether_brick_stairs": {"materials": {"minecraft:nether_bricks": 6}, "grid": "3x3", "yield": 4},
    "minecraft:nether_brick_wall": {"materials": {"minecraft:nether_bricks": 6}, "grid": "3x3", "yield": 6},
    "minecraft:nether_bricks": {"materials": {"minecraft:nether_brick": 4}, "grid": "2x2", "yield": 1},
    "minecraft:nether_wart_block": {"materials": {"minecraft:nether_wart": 9}, "grid": "2x2", "yield": 1},
    "minecraft:netherite_block": {"materials": {"minecraft:netherite_ingot": 9}, "grid": "3x3", "yield": 1},
    "minecraft:note_block": {"materials": {"minecraft:oak_planks": 8, "minecraft:redstone": 1}, "grid": "3x3", "yield": 1},
    "minecraft:oak_boat": {"materials": {"minecraft:oak_planks": 5}, "grid": "3x3", "yield": 1},
    "minecraft:oak_button": {"materials": {"minecraft:oak_planks": 1}, "grid": "2x2", "yield": 1},
    "minecraft:oak_chest_boat": {"materials": {"minecraft:chest": 1, "minecraft:oak_boat": 1}, "grid": "2x2", "yield": 1},
    "minecraft:oak_door": {"materials": {"minecraft:oak_planks": 6}, "grid": "3x3", "yield": 3},
    "minecraft:oak_fence": {"materials": {"minecraft:oak_planks": 4, "minecraft:stick": 2}, "grid": "3x3", "yield": 3},
    "minecraft:oak_fence_gate": {"materials": {"minecraft:stick": 4, "minecraft:oak_planks": 2}, "grid": "3x3", "yield": 1},
    "minecraft:oak_hanging_sign": {"materials": {"minecraft:chain": 2, "minecraft:stripped_oak_log": 6}, "grid": "3x3", "yield": 6},
    "minecraft:oak_planks": {"materials": {"minecraft:oak_log": 1}, "grid": "2x2", "yield": 4},
    "minecraft:oak_pressure_plate": {"materials": {"minecraft:oak_planks": 2}, "grid": "2x2", "yield": 1},
    "minecraft:oak_sign": {"materials": {"minecraft:oak_planks": 6, "minecraft:stick": 1}, "grid": "3x3", "yield": 3},
    "minecraft:oak_slab": {"materials": {"minecraft:oak_planks": 3}, "grid": "3x3", "yield": 6},
    "minecraft:oak_stairs": {"materials": {"minecraft:oak_planks": 6}, "grid": "3x3", "yield": 4},
    "minecraft:oak_trapdoor": {"materials": {"minecraft:oak_planks": 6}, "grid": "3x3", "yield": 2},
    "minecraft:oak_wood": {"materials": {"minecraft:oak_log": 4}, "grid": "2x2", "yield": 3},
    "minecraft:observer": {"materials": {"minecraft:cobblestone": 6, "minecraft:redstone": 2, "minecraft:quartz": 1}, "grid": "3x3", "yield": 1},
    "minecraft:orange_banner": {"materials": {"minecraft:orange_wool": 6, "minecraft:stick": 1}, "grid": "3x3", "yield": 1},
    "minecraft:orange_bed": {"materials": {"minecraft:orange_dye": 1, "minecraft:black_bed": 1}, "grid": "2x2", "yield": 1},
    "minecraft:orange_candle": {"materials": {"minecraft:candle": 1, "minecraft:orange_dye": 1}, "grid": "2x2", "yield": 1},
    "minecraft:orange_carpet": {"materials": {"minecraft:orange_wool": 2}, "grid": "2x2", "yield": 3},
    "minecraft:orange_concrete_powder": {"materials": {"minecraft:orange_dye": 1, "minecraft:sand": 4, "minecraft:gravel": 4}, "grid": "2x2", "yield": 8},
    "minecraft:orange_dye": {"materials": {"minecraft:orange_tulip": 1}, "grid": "2x2", "yield": 1},
    "minecraft:orange_stained_glass": {"materials": {"minecraft:glass": 8, "minecraft:orange_dye": 1}, "grid": "3x3", "yield": 8},
    "minecraft:orange_stained_glass_pane": {"materials": {"minecraft:orange_stained_glass": 6}, "grid": "3x3", "yield": 16},
    "minecraft:orange_terracotta": {"materials": {"minecraft:terracotta": 8, "minecraft:orange_dye": 1}, "grid": "3x3", "yield": 8},
    "minecraft:orange_wool": {"materials": {"minecraft:orange_dye": 1, "minecraft:black_wool": 1}, "grid": "2x2", "yield": 1},
    "minecraft:oxidized_cut_copper": {"materials": {"minecraft:oxidized_copper": 4}, "grid": "2x2", "yield": 4},
    "minecraft:oxidized_cut_copper_slab": {"materials": {"minecraft:oxidized_cut_copper": 3}, "grid": "3x3", "yield": 6},
    "minecraft:oxidized_cut_copper_stairs": {"materials": {"minecraft:oxidized_cut_copper": 6}, "grid": "3x3", "yield": 4},
    "minecraft:packed_ice": {"materials": {"minecraft:ice": 9}, "grid": "2x2", "yield": 1},
    "minecraft:packed_mud": {"materials": {"minecraft:mud": 1, "minecraft:wheat": 1}, "grid": "2x2", "yield": 1},
    "minecraft:painting": {"materials": {"minecraft:stick": 8, "minecraft:white_wool": 1}, "grid": "3x3", "yield": 1},
    "minecraft:paper": {"materials": {"minecraft:sugar_cane": 3}, "grid": "3x3", "yield": 3},
    "minecraft:pink_banner": {"materials": {"minecraft:pink_wool": 6, "minecraft:stick": 1}, "grid": "3x3", "yield": 1},
    "minecraft:pink_bed": {"materials": {"minecraft:pink_dye": 1, "minecraft:black_bed": 1}, "grid": "2x2", "yield": 1},
    "minecraft:pink_candle": {"materials": {"minecraft:candle": 1, "minecraft:pink_dye": 1}, "grid": "2x2", "yield": 1},
    "minecraft:pink_carpet": {"materials": {"minecraft:pink_wool": 2}, "grid": "2x2", "yield": 3},
    "minecraft:pink_concrete_powder": {"materials": {"minecraft:pink_dye": 1, "minecraft:sand": 4, "minecraft:gravel": 4}, "grid": "2x2", "yield": 8},
    "minecraft:pink_dye": {"materials": {"minecraft:peony": 1}, "grid": "2x2", "yield": 2},
    "minecraft:pink_stained_glass": {"materials": {"minecraft:glass": 8, "minecraft:pink_dye": 1}, "grid": "3x3", "yield": 8},
    "minecraft:pink_stained_glass_pane": {"materials": {"minecraft:pink_stained_glass": 6}, "grid": "3x3", "yield": 16},
    "minecraft:pink_terracotta": {"materials": {"minecraft:terracotta": 8, "minecraft:pink_dye": 1}, "grid": "3x3", "yield": 8},
    "minecraft:pink_wool": {"materials": {"minecraft:pink_dye": 1, "minecraft:black_wool": 1}, "grid": "2x2", "yield": 1},
    "minecraft:piston": {"materials": {"minecraft:oak_planks": 3, "minecraft:cobblestone": 4, "minecraft:iron_ingot": 1, "minecraft:redstone": 1}, "grid": "3x3", "yield": 1},
    "minecraft:polished_andesite": {"materials": {"minecraft:andesite": 4}, "grid": "2x2", "yield": 4},
    "minecraft:polished_andesite_slab": {"materials": {"minecraft:polished_andesite": 3}, "grid": "3x3", "yield": 6},
    "minecraft:polished_andesite_stairs": {"materials": {"minecraft:polished_andesite": 6}, "grid": "3x3", "yield": 4},
    "minecraft:polished_basalt": {"materials": {"minecraft:basalt": 4}, "grid": "2x2", "yield": 4},
    "minecraft:polished_blackstone": {"materials": {"minecraft:blackstone": 4}, "grid": "2x2", "yield": 4},
    "minecraft:polished_blackstone_brick_slab": {"materials": {"minecraft:polished_blackstone_bricks": 3}, "grid": "3x3", "yield": 6},
    "minecraft:polished_blackstone_brick_stairs": {"materials": {"minecraft:polished_blackstone_bricks": 6}, "grid": "3x3", "yield": 4},
    "minecraft:polished_blackstone_brick_wall": {"materials": {"minecraft:polished_blackstone_bricks": 6}, "grid": "3x3", "yield": 6},
    "minecraft:polished_blackstone_bricks": {"materials": {"minecraft:polished_blackstone": 4}, "grid": "2x2", "yield": 4},
    "minecraft:polished_blackstone_button": {"materials": {"minecraft:polished_blackstone": 1}, "grid": "2x2", "yield": 1},
    "minecraft:polished_blackstone_pressure_plate": {"materials": {"minecraft:polished_blackstone": 2}, "grid": "2x2", "yield": 1},
    "minecraft:polished_blackstone_slab": {"materials": {"minecraft:polished_blackstone": 3}, "grid": "3x3", "yield": 6},
    "minecraft:polished_blackstone_stairs": {"materials": {"minecraft:polished_blackstone": 6}, "grid": "3x3", "yield": 4},
    "minecraft:polished_blackstone_wall": {"materials": {"minecraft:polished_blackstone": 6}, "grid": "3x3", "yield": 6},
    "minecraft:polished_deepslate": {"materials": {"minecraft:cobbled_deepslate": 4}, "grid": "2x2", "yield": 4},
    "minecraft:polished_deepslate_slab": {"materials": {"minecraft:polished_deepslate": 3}, "grid": "3x3", "yield": 6},
    "minecraft:polished_deepslate_stairs": {"materials": {"minecraft:polished_deepslate": 6}, "grid": "3x3", "yield": 4},
    "minecraft:polished_deepslate_wall": {"materials": {"minecraft:polished_deepslate": 6}, "grid": "3x3", "yield": 6},
    "minecraft:polished_diorite": {"materials": {"minecraft:diorite": 4}, "grid": "2x2", "yield": 4},
    "minecraft:polished_diorite_slab": {"materials": {"minecraft:polished_diorite": 3}, "grid": "3x3", "yield": 6},
    "minecraft:polished_diorite_stairs": {"materials": {"minecraft:polished_diorite": 6}, "grid": "3x3", "yield": 4},
    "minecraft:polished_granite": {"materials": {"minecraft:granite": 4}, "grid": "2x2", "yield": 4},
    "minecraft:polished_granite_slab": {"materials": {"minecraft:polished_granite": 3}, "grid": "3x3", "yield": 6},
    "minecraft:polished_granite_stairs": {"materials": {"minecraft:polished_granite": 6}, "grid": "3x3", "yield": 4},
    "minecraft:powered_rail": {"materials": {"minecraft:gold_ingot": 6, "minecraft:stick": 1, "minecraft:redstone": 1}, "grid": "3x3", "yield": 6},
    "minecraft:prismarine": {"materials": {"minecraft:prismarine_shard": 4}, "grid": "2x2", "yield": 1},
    "minecraft:prismarine_brick_slab": {"materials": {"minecraft:prismarine_bricks": 3}, "grid": "3x3", "yield": 6},
    "minecraft:prismarine_brick_stairs": {"materials": {"minecraft:prismarine_bricks": 6}, "grid": "3x3", "yield": 4},
    "minecraft:prismarine_bricks": {"materials": {"minecraft:prismarine_shard": 9}, "grid": "2x2", "yield": 1},
    "minecraft:prismarine_slab": {"materials": {"minecraft:prismarine": 3}, "grid": "3x3", "yield": 6},
    "minecraft:prismarine_stairs": {"materials": {"minecraft:prismarine": 6}, "grid": "3x3", "yield": 4},
    "minecraft:prismarine_wall": {"materials": {"minecraft:prismarine": 6}, "grid": "3x3", "yield": 6},
    "minecraft:pumpkin_pie": {"materials": {"minecraft:pumpkin": 1, "minecraft:sugar": 1, "minecraft:egg": 1}, "grid": "2x2", "yield": 1},
    "minecraft:pumpkin_seeds": {"materials": {"minecraft:pumpkin": 1}, "grid": "2x2", "yield": 4},
    "minecraft:purple_banner": {"materials": {"minecraft:purple_wool": 6, "minecraft:stick": 1}, "grid": "3x3", "yield": 1},
    "minecraft:purple_bed": {"materials": {"minecraft:purple_dye": 1, "minecraft:black_bed": 1}, "grid": "2x2", "yield": 1},
    "minecraft:purple_candle": {"materials": {"minecraft:candle": 1, "minecraft:purple_dye": 1}, "grid": "2x2", "yield": 1},
    "minecraft:purple_carpet": {"materials": {"minecraft:purple_wool": 2}, "grid": "2x2", "yield": 3},
    "minecraft:purple_concrete_powder": {"materials": {"minecraft:purple_dye": 1, "minecraft:sand": 4, "minecraft:gravel": 4}, "grid": "2x2", "yield": 8},
    "minecraft:purple_dye": {"materials": {"minecraft:blue_dye": 1, "minecraft:red_dye": 1}, "grid": "2x2", "yield": 2},
    "minecraft:purple_stained_glass": {"materials": {"minecraft:glass": 8, "minecraft:purple_dye": 1}, "grid": "3x3", "yield": 8},
    "minecraft:purple_stained_glass_pane": {"materials": {"minecraft:purple_stained_glass": 6}, "grid": "3x3", "yield": 16},
    "minecraft:purple_terracotta": {"materials": {"minecraft:terracotta": 8, "minecraft:purple_dye": 1}, "grid": "3x3", "yield": 8},
    "minecraft:purple_wool": {"materials": {"minecraft:purple_dye": 1, "minecraft:black_wool": 1}, "grid": "2x2", "yield": 1},
    "minecraft:purpur_block": {"materials": {"minecraft:popped_chorus_fruit": 4}, "grid": "2x2", "yield": 4},
    "minecraft:purpur_pillar": {"materials": {"minecraft:purpur_slab": 2}, "grid": "2x2", "yield": 1},
    "minecraft:purpur_slab": {"materials": {"minecraft:purpur_block": 3}, "grid": "3x3", "yield": 6},
    "minecraft:purpur_stairs": {"materials": {"minecraft:purpur_block": 6}, "grid": "3x3", "yield": 4},
    "minecraft:quartz_block": {"materials": {"minecraft:quartz": 4}, "grid": "2x2", "yield": 1},
    "minecraft:quartz_bricks": {"materials": {"minecraft:quartz_block": 4}, "grid": "2x2", "yield": 4},
    "minecraft:quartz_pillar": {"materials": {"minecraft:quartz_block": 2}, "grid": "2x2", "yield": 2},
    "minecraft:quartz_slab": {"materials": {"minecraft:chiseled_quartz_block": 3}, "grid": "3x3", "yield": 6},
    "minecraft:quartz_stairs": {"materials": {"minecraft:chiseled_quartz_block": 6}, "grid": "3x3", "yield": 4},
    "minecraft:rabbit_stew": {"materials": {"minecraft:baked_potato": 1, "minecraft:cooked_rabbit": 1, "minecraft:bowl": 1, "minecraft:carrot": 1, "minecraft:brown_mushroom": 1}, "grid": "3x3", "yield": 1},
    "minecraft:rail": {"materials": {"minecraft:iron_ingot": 6, "minecraft:stick": 1}, "grid": "3x3", "yield": 16},
    "minecraft:raw_copper_block": {"materials": {"minecraft:raw_copper": 9}, "grid": "3x3", "yield": 1},
    "minecraft:raw_gold_block": {"materials": {"minecraft:raw_gold": 9}, "grid": "3x3", "yield": 1},
    "minecraft:raw_iron_block": {"materials": {"minecraft:raw_iron": 9}, "grid": "3x3", "yield": 1},
    "minecraft:recovery_compass": {"materials": {"minecraft:echo_shard": 8, "minecraft:compass": 1}, "grid": "3x3", "yield": 1},
    "minecraft:red_banner": {"materials": {"minecraft:red_wool": 6, "minecraft:stick": 1}, "grid": "3x3", "yield": 1},
    "minecraft:red_bed": {"materials": {"minecraft:red_dye": 1, "minecraft:black_bed": 1}, "grid": "2x2", "yield": 1},
    "minecraft:red_candle": {"materials": {"minecraft:candle": 1, "minecraft:red_dye": 1}, "grid": "2x2", "yield": 1},
    "minecraft:red_carpet": {"materials": {"minecraft:red_wool": 2}, "grid": "2x2", "yield": 3},
    "minecraft:red_concrete_powder": {"materials": {"minecraft:red_dye": 1, "minecraft:sand": 4, "minecraft:gravel": 4}, "grid": "2x2", "yield": 8},
    "minecraft:red_dye": {"materials": {"minecraft:beetroot": 1}, "grid": "2x2", "yield": 1},
    "minecraft:red_nether_brick_slab": {"materials": {"minecraft:red_nether_bricks": 3}, "grid": "3x3", "yield": 6},
    "minecraft:red_nether_brick_stairs": {"materials": {"minecraft:red_nether_bricks": 6}, "grid": "3x3", "yield": 4},
    "minecraft:red_nether_brick_wall": {"materials": {"minecraft:red_nether_bricks": 6}, "grid": "3x3", "yield": 6},
    "minecraft:red_nether_bricks": {"materials": {"minecraft:nether_brick": 2, "minecraft:nether_wart": 2}, "grid": "2x2", "yield": 1},
    "minecraft:red_sandstone": {"materials": {"minecraft:red_sand": 4}, "grid": "2x2", "yield": 1},
    "minecraft:red_sandstone_slab": {"materials": {"minecraft:red_sandstone": 3}, "grid": "3x3", "yield": 6},
    "minecraft:red_sandstone_stairs": {"materials": {"minecraft:red_sandstone": 6}, "grid": "3x3", "yield": 4},
    "minecraft:red_sandstone_wall": {"materials": {"minecraft:red_sandstone": 6}, "grid": "3x3", "yield": 6},
    "minecraft:red_stained_glass": {"materials": {"minecraft:glass": 8, "minecraft:red_dye": 1}, "grid": "3x3", "yield": 8},
    "minecraft:red_stained_glass_pane": {"materials": {"minecraft:red_stained_glass": 6}, "grid": "3x3", "yield": 16},
    "minecraft:red_terracotta": {"materials": {"minecraft:terracotta": 8, "minecraft:red_dye": 1}, "grid": "3x3", "yield": 8},
    "minecraft:red_wool": {"materials": {"minecraft:red_dye": 1, "minecraft:black_wool": 1}, "grid": "2x2", "yield": 1},
    "minecraft:redstone_block": {"materials": {"minecraft:redstone": 9}, "grid": "3x3", "yield": 1},
    "minecraft:redstone_lamp": {"materials": {"minecraft:redstone": 4, "minecraft:glowstone": 1}, "grid": "3x3", "yield": 1},
    "minecraft:redstone_torch": {"materials": {"minecraft:redstone": 1, "minecraft:stick": 1}, "grid": "2x2", "yield": 1},
    "minecraft:repeater": {"materials": {"minecraft:redstone_torch": 2, "minecraft:redstone": 1, "minecraft:stone": 3}, "grid": "3x3", "yield": 1},
    "minecraft:respawn_anchor": {"materials": {"minecraft:crying_obsidian": 6, "minecraft:glowstone": 3}, "grid": "3x3", "yield": 1},
    "minecraft:sandstone": {"materials": {"minecraft:sand": 4}, "grid": "2x2", "yield": 1},
    "minecraft:sandstone_slab": {"materials": {"minecraft:sandstone": 3}, "grid": "3x3", "yield": 6},
    "minecraft:sandstone_stairs": {"materials": {"minecraft:sandstone": 6}, "grid": "3x3", "yield": 4},
    "minecraft:sandstone_wall": {"materials": {"minecraft:sandstone": 6}, "grid": "3x3", "yield": 6},
    "minecraft:scaffolding": {"materials": {"minecraft:bamboo": 6, "minecraft:string": 1}, "grid": "3x3", "yield": 6},
    "minecraft:sea_lantern": {"materials": {"minecraft:prismarine_shard": 4, "minecraft:prismarine_crystals": 5}, "grid": "3x3", "yield": 1},
    "minecraft:shears": {"materials": {"minecraft:iron_ingot": 2}, "grid": "2x2", "yield": 1},
    "minecraft:shield": {"materials": {"minecraft:oak_planks": 6, "minecraft:iron_ingot": 1}, "grid": "3x3", "yield": 1},
    "minecraft:shulker_box": {"materials": {"minecraft:shulker_shell": 2, "minecraft:chest": 1}, "grid": "3x3", "yield": 1},
    "minecraft:skull_banner_pattern": {"materials": {"minecraft:paper": 1, "minecraft:wither_skeleton_skull": 1}, "grid": "2x2", "yield": 1},
    "minecraft:slime_ball": {"materials": {"minecraft:slime_block": 1}, "grid": "2x2", "yield": 9},
    "minecraft:slime_block": {"materials": {"minecraft:slime_ball": 9}, "grid": "3x3", "yield": 1},
    "minecraft:smithing_table": {"materials": {"minecraft:iron_ingot": 2, "minecraft:oak_planks": 4}, "grid": "3x3", "yield": 1},
    "minecraft:smoker": {"materials": {"minecraft:dark_oak_log": 4, "minecraft:furnace": 1}, "grid": "3x3", "yield": 1},
    "minecraft:smooth_quartz_slab": {"materials": {"minecraft:smooth_quartz": 3}, "grid": "3x3", "yield": 6},
    "minecraft:smooth_quartz_stairs": {"materials": {"minecraft:smooth_quartz": 6}, "grid": "3x3", "yield": 4},
    "minecraft:smooth_red_sandstone_slab": {"materials": {"minecraft:smooth_red_sandstone": 3}, "grid": "3x3", "yield": 6},
    "minecraft:smooth_red_sandstone_stairs": {"materials": {"minecraft:smooth_red_sandstone": 6}, "grid": "3x3", "yield": 4},
    "minecraft:smooth_sandstone_slab": {"materials": {"minecraft:smooth_sandstone": 3}, "grid": "3x3", "yield": 6},
    "minecraft:smooth_sandstone_stairs": {"materials": {"minecraft:smooth_sandstone": 6}, "grid": "3x3", "yield": 4},
    "minecraft:smooth_stone_slab": {"materials": {"minecraft:smooth_stone": 3}, "grid": "3x3", "yield": 6},
    "minecraft:snow": {"materials": {"minecraft:snow_block": 3}, "grid": "3x3", "yield": 6},
    "minecraft:snow_block": {"materials": {"minecraft:snowball": 4}, "grid": "2x2", "yield": 1},
    "minecraft:soul_campfire": {"materials": {"minecraft:stick": 3, "minecraft:soul_sand": 1, "minecraft:dark_oak_log": 3}, "grid": "3x3", "yield": 1},
    "minecraft:soul_lantern": {"materials": {"minecraft:iron_nugget": 8, "minecraft:soul_torch": 1}, "grid": "3x3", "yield": 1},
    "minecraft:soul_torch": {"materials": {"minecraft:coal": 1, "minecraft:stick": 1, "minecraft:soul_sand": 1}, "grid": "3x3", "yield": 4},
    "minecraft:spectral_arrow": {"materials": {"minecraft:glowstone_dust": 4, "minecraft:arrow": 1}, "grid": "3x3", "yield": 2},
    "minecraft:spruce_boat": {"materials": {"minecraft:spruce_planks": 5}, "grid": "3x3", "yield": 1},
    "minecraft:spruce_button": {"materials": {"minecraft:spruce_planks": 1}, "grid": "2x2", "yield": 1},
    "minecraft:spruce_chest_boat": {"materials": {"minecraft:chest": 1, "minecraft:spruce_boat": 1}, "grid": "2x2", "yield": 1},
    "minecraft:spruce_door": {"materials": {"minecraft:spruce_planks": 6}, "grid": "3x3", "yield": 3},
    "minecraft:spruce_fence": {"materials": {"minecraft:spruce_planks": 4, "minecraft:stick": 2}, "grid": "3x3", "yield": 3},
    "minecraft:spruce_fence_gate": {"materials": {"minecraft:stick": 4, "minecraft:spruce_planks": 2}, "grid": "3x3", "yield": 1},
    "minecraft:spruce_hanging_sign": {"materials": {"minecraft:chain": 2, "minecraft:stripped_spruce_log": 6}, "grid": "3x3", "yield": 6},
    "minecraft:spruce_planks": {"materials": {"minecraft:spruce_log": 1}, "grid": "2x2", "yield": 4},
    "minecraft:spruce_pressure_plate": {"materials": {"minecraft:spruce_planks": 2}, "grid": "2x2", "yield": 1},
    "minecraft:spruce_sign": {"materials": {"minecraft:spruce_planks": 6, "minecraft:stick": 1}, "grid": "3x3", "yield": 3},
    "minecraft:spruce_slab": {"materials": {"minecraft:spruce_planks": 3}, "grid": "3x3", "yield": 6},
    "minecraft:spruce_stairs": {"materials": {"minecraft:spruce_planks": 6}, "grid": "3x3", "yield": 4},
    "minecraft:spruce_trapdoor": {"materials": {"minecraft:spruce_planks": 6}, "grid": "3x3", "yield": 2},
    "minecraft:spruce_wood": {"materials": {"minecraft:spruce_log": 4}, "grid": "2x2", "yield": 3},
    "minecraft:spyglass": {"materials": {"minecraft:amethyst_shard": 1, "minecraft:copper_ingot": 2}, "grid": "3x3", "yield": 1},
    "minecraft:stick": {"materials": {"minecraft:oak_planks": 2}, "grid": "2x2", "yield": 4},
    "minecraft:sticky_piston": {"materials": {"minecraft:slime_ball": 1, "minecraft:piston": 1}, "grid": "2x2", "yield": 1},
    "minecraft:stone_axe": {"materials": {"minecraft:cobblestone": 3, "minecraft:stick": 2}, "grid": "3x3", "yield": 1},
    "minecraft:stone_brick_slab": {"materials": {"minecraft:stone_bricks": 3}, "grid": "3x3", "yield": 6},
    "minecraft:stone_brick_stairs": {"materials": {"minecraft:stone_bricks": 6}, "grid": "3x3", "yield": 4},
    "minecraft:stone_brick_wall": {"materials": {"minecraft:stone_bricks": 6}, "grid": "3x3", "yield": 6},
    "minecraft:stone_bricks": {"materials": {"minecraft:stone": 4}, "grid": "2x2", "yield": 4},
    "minecraft:stone_button": {"materials": {"minecraft:stone": 1}, "grid": "2x2", "yield": 1},
    "minecraft:stone_hoe": {"materials": {"minecraft:cobblestone": 2, "minecraft:stick": 2}, "grid": "3x3", "yield": 1},
    "minecraft:stone_pickaxe": {"materials": {"minecraft:cobblestone": 3, "minecraft:stick": 2}, "grid": "3x3", "yield": 1},
    "minecraft:stone_pressure_plate": {"materials": {"minecraft:stone": 2}, "grid": "2x2", "yield": 1},
    "minecraft:stone_shovel": {"materials": {"minecraft:cobblestone": 1, "minecraft:stick": 2}, "grid": "3x3", "yield": 1},
    "minecraft:stone_slab": {"materials": {"minecraft:stone": 3}, "grid": "3x3", "yield": 6},
    "minecraft:stone_stairs": {"materials": {"minecraft:stone": 6}, "grid": "3x3", "yield": 4},
    "minecraft:stone_sword": {"materials": {"minecraft:cobblestone": 2, "minecraft:stick": 1}, "grid": "3x3", "yield": 1},
    "minecraft:stonecutter": {"materials": {"minecraft:iron_ingot": 1, "minecraft:stone": 3}, "grid": "3x3", "yield": 1},
    "minecraft:stripped_acacia_wood": {"materials": {"minecraft:stripped_acacia_log": 4}, "grid": "2x2", "yield": 3},
    "minecraft:stripped_birch_wood": {"materials": {"minecraft:stripped_birch_log": 4}, "grid": "2x2", "yield": 3},
    "minecraft:stripped_cherry_wood": {"materials": {"minecraft:stripped_cherry_log": 4}, "grid": "2x2", "yield": 3},
    "minecraft:stripped_crimson_hyphae": {"materials": {"minecraft:stripped_crimson_stem": 4}, "grid": "2x2", "yield": 3},
    "minecraft:stripped_dark_oak_wood": {"materials": {"minecraft:stripped_dark_oak_log": 4}, "grid": "2x2", "yield": 3},
    "minecraft:stripped_jungle_wood": {"materials": {"minecraft:stripped_jungle_log": 4}, "grid": "2x2", "yield": 3},
    "minecraft:stripped_mangrove_wood": {"materials": {"minecraft:stripped_mangrove_log": 4}, "grid": "2x2", "yield": 3},
    "minecraft:stripped_oak_wood": {"materials": {"minecraft:stripped_oak_log": 4}, "grid": "2x2", "yield": 3},
    "minecraft:stripped_spruce_wood": {"materials": {"minecraft:stripped_spruce_log": 4}, "grid": "2x2", "yield": 3},
    "minecraft:stripped_warped_hyphae": {"materials": {"minecraft:stripped_warped_stem": 4}, "grid": "2x2", "yield": 3},
    "minecraft:sugar": {"materials": {"minecraft:honey_bottle": 1}, "grid": "2x2", "yield": 3},
    "minecraft:target": {"materials": {"minecraft:redstone": 4, "minecraft:hay_block": 1}, "grid": "3x3", "yield": 1},
    "minecraft:tinted_glass": {"materials": {"minecraft:amethyst_shard": 4, "minecraft:glass": 1}, "grid": "3x3", "yield": 2},
    "minecraft:tnt": {"materials": {"minecraft:gunpowder": 5, "minecraft:sand": 4}, "grid": "3x3", "yield": 1},
    "minecraft:tnt_minecart": {"materials": {"minecraft:tnt": 1, "minecraft:minecart": 1}, "grid": "2x2", "yield": 1},
    "minecraft:torch": {"materials": {"minecraft:coal": 1, "minecraft:stick": 1}, "grid": "2x2", "yield": 4},
    "minecraft:trapped_chest": {"materials": {"minecraft:chest": 1, "minecraft:tripwire_hook": 1}, "grid": "2x2", "yield": 1},
    "minecraft:tripwire_hook": {"materials": {"minecraft:iron_ingot": 1, "minecraft:stick": 1, "minecraft:oak_planks": 1}, "grid": "3x3", "yield": 2},
    "minecraft:turtle_helmet": {"materials": {"minecraft:scute": 5}, "grid": "3x3", "yield": 1},
    "minecraft:warped_button": {"materials": {"minecraft:warped_planks": 1}, "grid": "2x2", "yield": 1},
    "minecraft:warped_door": {"materials": {"minecraft:warped_planks": 6}, "grid": "3x3", "yield": 3},
    "minecraft:warped_fence": {"materials": {"minecraft:warped_planks": 4, "minecraft:stick": 2}, "grid": "3x3", "yield": 3},
    "minecraft:warped_fence_gate": {"materials": {"minecraft:stick": 4, "minecraft:warped_planks": 2}, "grid": "3x3", "yield": 1},
    "minecraft:warped_fungus_on_a_stick": {"materials": {"minecraft:fishing_rod": 1, "minecraft:warped_fungus": 1}, "grid": "2x2", "yield": 1},
    "minecraft:warped_hanging_sign": {"materials": {"minecraft:chain": 2, "minecraft:stripped_warped_stem": 6}, "grid": "3x3", "yield": 6},
    "minecraft:warped_hyphae": {"materials": {"minecraft:warped_stem": 4}, "grid": "2x2", "yield": 3},
    "minecraft:warped_planks": {"materials": {"minecraft:warped_stem": 1}, "grid": "2x2", "yield": 4},
    "minecraft:warped_pressure_plate": {"materials": {"minecraft:warped_planks": 2}, "grid": "2x2", "yield": 1},
    "minecraft:warped_sign": {"materials": {"minecraft:warped_planks": 6, "minecraft:stick": 1}, "grid": "3x3", "yield": 3},
    "minecraft:warped_slab": {"materials": {"minecraft:warped_planks": 3}, "grid": "3x3", "yield": 6},
    "minecraft:warped_stairs": {"materials": {"minecraft:warped_planks": 6}, "grid": "3x3", "yield": 4},
    "minecraft:warped_trapdoor": {"materials": {"minecraft:warped_planks": 6}, "grid": "3x3", "yield": 2},
    "minecraft:waxed_copper_block": {"materials": {"minecraft:copper_block": 1, "minecraft:honeycomb": 1}, "grid": "2x2", "yield": 1},
    "minecraft:waxed_cut_copper": {"materials": {"minecraft:waxed_copper_block": 4}, "grid": "2x2", "yield": 4},
    "minecraft:waxed_cut_copper_slab": {"materials": {"minecraft:waxed_cut_copper": 3}, "grid": "3x3", "yield": 6},
    "minecraft:waxed_cut_copper_stairs": {"materials": {"minecraft:waxed_cut_copper": 6}, "grid": "3x3", "yield": 4},
    "minecraft:waxed_exposed_copper": {"materials": {"minecraft:exposed_copper": 1, "minecraft:honeycomb": 1}, "grid": "2x2", "yield": 1},
    "minecraft:waxed_exposed_cut_copper": {"materials": {"minecraft:waxed_exposed_copper": 4}, "grid": "2x2", "yield": 4},
    "minecraft:waxed_exposed_cut_copper_slab": {"materials": {"minecraft:waxed_exposed_cut_copper": 3}, "grid": "3x3", "yield": 6},
    "minecraft:waxed_exposed_cut_copper_stairs": {"materials": {"minecraft:waxed_exposed_cut_copper": 6}, "grid": "3x3", "yield": 4},
    "minecraft:waxed_oxidized_copper": {"materials": {"minecraft:oxidized_copper": 1, "minecraft:honeycomb": 1}, "grid": "2x2", "yield": 1},
    "minecraft:waxed_oxidized_cut_copper": {"materials": {"minecraft:waxed_oxidized_copper": 4}, "grid": "2x2", "yield": 4},
    "minecraft:waxed_oxidized_cut_copper_slab": {"materials": {"minecraft:waxed_oxidized_cut_copper": 3}, "grid": "3x3", "yield": 6},
    "minecraft:waxed_oxidized_cut_copper_stairs": {"materials": {"minecraft:waxed_oxidized_cut_copper": 6}, "grid": "3x3", "yield": 4},
    "minecraft:waxed_weathered_copper": {"materials": {"minecraft:weathered_copper": 1, "minecraft:honeycomb": 1}, "grid": "2x2", "yield": 1},
    "minecraft:waxed_weathered_cut_copper": {"materials": {"minecraft:waxed_weathered_copper": 4}, "grid": "2x2", "yield": 4},
    "minecraft:waxed_weathered_cut_copper_slab": {"materials": {"minecraft:waxed_weathered_cut_copper": 3}, "grid": "3x3", "yield": 6},
    "minecraft:waxed_weathered_cut_copper_stairs": {"materials": {"minecraft:waxed_weathered_cut_copper": 6}, "grid": "3x3", "yield": 4},
    "minecraft:weathered_cut_copper": {"materials": {"minecraft:weathered_copper": 4}, "grid": "2x2", "yield": 4},
    "minecraft:weathered_cut_copper_slab": {"materials": {"minecraft:weathered_cut_copper": 3}, "grid": "3x3", "yield": 6},
    "minecraft:weathered_cut_copper_stairs": {"materials": {"minecraft:weathered_cut_copper": 6}, "grid": "3x3", "yield": 4},
    "minecraft:wheat": {"materials": {"minecraft:hay_block": 1}, "grid": "2x2", "yield": 9},
    "minecraft:white_banner": {"materials": {"minecraft:white_wool": 6, "minecraft:stick": 1}, "grid": "3x3", "yield": 1},
    "minecraft:white_bed": {"materials": {"minecraft:white_dye": 1, "minecraft:black_bed": 1}, "grid": "2x2", "yield": 1},
    "minecraft:white_candle": {"materials": {"minecraft:candle": 1, "minecraft:white_dye": 1}, "grid": "2x2", "yield": 1},
    "minecraft:white_carpet": {"materials": {"minecraft:white_wool": 2}, "grid": "2x2", "yield": 3},
    "minecraft:white_concrete_powder": {"materials": {"minecraft:white_dye": 1, "minecraft:sand": 4, "minecraft:gravel": 4}, "grid": "2x2", "yield": 8},
    "minecraft:white_dye": {"materials": {"minecraft:bone_meal": 1}, "grid": "2x2", "yield": 1},
    "minecraft:white_stained_glass": {"materials": {"minecraft:glass": 8, "minecraft:white_dye": 1}, "grid": "3x3", "yield": 8},
    "minecraft:white_stained_glass_pane": {"materials": {"minecraft:white_stained_glass": 6}, "grid": "3x3", "yield": 16},
    "minecraft:white_terracotta": {"materials": {"minecraft:terracotta": 8, "minecraft:white_dye": 1}, "grid": "3x3", "yield": 8},
    "minecraft:white_wool": {"materials": {"minecraft:string": 4}, "grid": "2x2", "yield": 1},
    "minecraft:wooden_axe": {"materials": {"minecraft:oak_planks": 3, "minecraft:stick": 2}, "grid": "3x3", "yield": 1},
    "minecraft:wooden_hoe": {"materials": {"minecraft:oak_planks": 2, "minecraft:stick": 2}, "grid": "3x3", "yield": 1},
    "minecraft:wooden_pickaxe": {"materials": {"minecraft:oak_planks": 3, "minecraft:stick": 2}, "grid": "3x3", "yield": 1},
    "minecraft:wooden_shovel": {"materials": {"minecraft:oak_planks": 1, "minecraft:stick": 2}, "grid": "3x3", "yield": 1},
    "minecraft:wooden_sword": {"materials": {"minecraft:oak_planks": 2, "minecraft:stick": 1}, "grid": "3x3", "yield": 1},
    "minecraft:writable_book": {"materials": {"minecraft:book": 1, "minecraft:ink_sac": 1, "minecraft:feather": 1}, "grid": "2x2", "yield": 1},
    "minecraft:yellow_banner": {"materials": {"minecraft:yellow_wool": 6, "minecraft:stick": 1}, "grid": "3x3", "yield": 1},
    "minecraft:yellow_bed": {"materials": {"minecraft:yellow_dye": 1, "minecraft:black_bed": 1}, "grid": "2x2", "yield": 1},
    "minecraft:yellow_candle": {"materials": {"minecraft:candle": 1, "minecraft:yellow_dye": 1}, "grid": "2x2", "yield": 1},
    "minecraft:yellow_carpet": {"materials": {"minecraft:yellow_wool": 2}, "grid": "2x2", "yield": 3},
    "minecraft:yellow_concrete_powder": {"materials": {"minecraft:yellow_dye": 1, "minecraft:sand": 4, "minecraft:gravel": 4}, "grid": "2x2", "yield": 8},
    "minecraft:yellow_dye": {"materials": {"minecraft:dandelion": 1}, "grid": "2x2", "yield": 1},
    "minecraft:yellow_stained_glass": {"materials": {"minecraft:glass": 8, "minecraft:yellow_dye": 1}, "grid": "3x3", "yield": 8},
    "minecraft:yellow_stained_glass_pane": {"materials": {"minecraft:yellow_stained_glass": 6}, "grid": "3x3", "yield": 16},
    "minecraft:yellow_terracotta": {"materials": {"minecraft:terracotta": 8, "minecraft:yellow_dye": 1}, "grid": "3x3", "yield": 8},
    "minecraft:yellow_wool": {"materials": {"minecraft:yellow_dye": 1, "minecraft:black_wool": 1}, "grid": "2x2", "yield": 1},
}
# ── 不可获取物品（明确告诉 LLM 不可合成/获取）────────────────────
UNOBTAINABLE = {
    "command_block", "chain_command_block", "repeating_command_block",
    "bedrock", "spawner", "barrier", "light", "structure_block",
    "structure_void", "jigsaw", "debug_stick", "command_block_minecart",
    "end_portal", "end_gateway", "nether_portal", "reinforced_deepslate",
}
UNOBTAINABLE_FULL = {f"minecraft:{x}" for x in UNOBTAINABLE}

# ── 工具进度链（木→石→铁→钻石：各级镐可挖的矿）─────────────────
PICKAXE_CHAIN = {
    "wooden_pickaxe":  {"mines": ["stone", "coal_ore"], "recipe": "minecraft:wooden_pickaxe", "desc": "木镐：圆石/煤"},
    "stone_pickaxe":   {"mines": ["iron_ore", "copper_ore"], "recipe": "minecraft:stone_pickaxe", "desc": "石镐：铁/铜"},
    "iron_pickaxe":    {"mines": ["gold_ore", "diamond_ore", "redstone_ore", "lapis_ore"], "recipe": "minecraft:iron_pickaxe", "desc": "铁镐：金/钻石/红石/青金石"},
    "diamond_pickaxe": {"mines": ["obsidian"], "recipe": "minecraft:diamond_pickaxe", "desc": "钻石镐：黑曜石"},
}

# ── 常用查询辅助 ────────────────────────────────────────────────

def recipe(item_id):
    """查配方（按物品 id 如 minecraft:oak_planks），返回 {materials, grid, yield, desc} 或 None。"""
    return RECIPES.get(item_id)


def is_unobtainable(item_id):
    """物品是否不可获取（命令方块/基岩等）。支持 minecraft:xxx 或裸名 xxx。"""
    if item_id in UNOBTAINABLE_FULL:
        return True
    if item_id.startswith("minecraft:") and item_id[len("minecraft:"):] in UNOBTAINABLE:
        return True
    if item_id in UNOBTAINABLE:
        return True
    return False


def needs_workbench(item_id) -> bool:
    """该配方是否需要工作台（3x3）。"""
    r = RECIPES.get(item_id)
    return bool(r and r["grid"] == "3x3")


def material_suffix(category) -> str:
    """材料类别 → 背包匹配后缀（_log/_planks/...）。"""
    m = MATERIAL_CATEGORIES.get(category)
    return m["suffix"] if m else category


def expand_material(category, state) -> str:
    """材料类别 → craft 用具体 id：expand 固定值直接用；None 按背包里找到的具体物品展开。

    例：log 类别 → 找背包里第一个 *_log（oak_log）→ 木板配方 oak_planks；
        plank 类别 → 找背包里第一个 *_planks。
    """
    from ._util import iter_items  # 延迟导入避免包初始化顺序问题
    m = MATERIAL_CATEGORIES.get(category)
    if m is None:
        return category
    if m["expand"]:
        return m["expand"]
    # 需要按背包展开：找到第一个匹配后缀的具体物品 id
    for entry in iter_items(state):
        iid = entry.get("id", "")
        if iid.endswith(m["suffix"]) and not iid.startswith("stripped_"):
            return iid
    return None
